package com.nanum.investment.api.v1;

import com.nanum.investment.common.exception.*;
import com.nanum.investment.common.response.ApiResponse;
import com.nanum.investment.common.web.TraceIdUtils;
import com.nanum.investment.domain.*;
import com.nanum.investment.repository.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/v1/admin/operations")
@Transactional(readOnly=true)
public class OperationalDataAdminController {
 private final TbHoldRepository holdings; private final TbRegBuyRepository regularBuys; private final TbCashRsvRepository cashReserves; private final TbAcctRepository accounts; private final TbStkRepository stocks;
 public OperationalDataAdminController(TbHoldRepository holdings,TbRegBuyRepository regularBuys,TbCashRsvRepository cashReserves,TbAcctRepository accounts,TbStkRepository stocks){this.holdings=holdings;this.regularBuys=regularBuys;this.cashReserves=cashReserves;this.accounts=accounts;this.stocks=stocks;}
 public record HoldingRequest(@NotNull Long accountId,@NotNull Long stockId,@NotNull @DecimalMin("0") BigDecimal holdingQuantity,@NotNull @DecimalMin("0") BigDecimal averagePrice,@NotNull @DecimalMin("0") BigDecimal exchangeRate,@DecimalMin("0") @DecimalMax("100") BigDecimal targetWeight,@NotNull HoldingStatus holdingStatus,@Size(max=1000) String memo,@Pattern(regexp="[YN]") String useYn){}
 public record HoldingRow(Long holdingId,Long accountId,AccountType accountType,Long stockId,String stockCode,String stockName,BigDecimal holdingQuantity,BigDecimal averagePrice,BigDecimal currentPrice,BigDecimal exchangeRate,BigDecimal evaluationAmount,BigDecimal profitLossRate,BigDecimal targetWeight,HoldingStatus holdingStatus,String memo,String useYn){}
 public record RegularBuyRequest(@NotNull Long accountId,@NotNull Long stockId,@NotNull BuyCycle buyCycle,@Pattern(regexp="(MON|TUE|WED|THU|FRI)(,(MON|TUE|WED|THU|FRI))*") String buyDayCode,@Min(1) @Max(31) Integer buyDayNumber,@Pattern(regexp="([1-9]|[12][0-9]|3[01])(,([1-9]|[12][0-9]|3[01]))*") String buyDayNumbers,@NotNull @Pattern(regexp="AMOUNT|QUANTITY") String buyBasis,@NotNull @DecimalMin("0") BigDecimal minimumBuyAmount,@DecimalMin("0") BigDecimal maximumBuyAmount,@DecimalMin("0") BigDecimal baseBuyQuantity,@DecimalMin("0") BigDecimal buyQuantity,@NotNull @DecimalMin("0") BigDecimal maximumMultiplier,@NotNull RegularBuyStatus buyStatus,@Size(max=500) String pauseReason,@Pattern(regexp="[YN]") String userPauseYn,@Pattern(regexp="[YN]") String autoCalculateYn,@Pattern(regexp="[YN]") String useYn){}
 public record RegularBuyRow(String regularBuyKey,Long accountId,AccountType accountType,Long stockId,String stockCode,String stockName,BuyCycle buyCycle,String buyDayCode,Integer buyDayNumber,String buyDayNumbers,String buyBasis,BigDecimal minimumBuyAmount,BigDecimal maximumBuyAmount,BigDecimal baseBuyQuantity,BigDecimal buyQuantity,BigDecimal maximumMultiplier,BigDecimal recommendedBuyAmount,RegularBuyStatus buyStatus,String pauseReason,String userPauseYn,String autoCalculateYn,String useYn){}
 public record CashReserveRequest(@NotNull Long accountId,@NotNull @DecimalMin("0") BigDecimal reserveAmount,@NotNull @DecimalMin("0") BigDecimal accumulatedAmount,@NotNull @DecimalMin("0") BigDecimal usedAmount,LocalDate lastTransactionDate){}
 public record CashReserveRow(Long cashReserveId,Long accountId,AccountType accountType,BigDecimal reserveAmount,BigDecimal accumulatedAmount,BigDecimal usedAmount,BigDecimal availableAmount,LocalDate lastTransactionDate,Long version){}
 @GetMapping("/holdings") public ApiResponse<List<HoldingRow>> holdings(HttpServletRequest r){return ok(holdings.findAll().stream().filter(x->"N".equals(x.getDeleteYn())).map(this::row).toList(),r);}
 @PostMapping("/holdings") @Transactional public ApiResponse<HoldingRow> createHolding(@Valid @RequestBody HoldingRequest b,HttpServletRequest r){if(holdings.findByAccount_AccountIdAndStock_StockIdAndDeleteYn(b.accountId(),b.stockId(),"N").isPresent())throw new BusinessException(ErrorCode.DUPLICATE_RESOURCE);TbHold x=new TbHold();apply(x,b);return ok(row(holdings.save(x)),r);}
 @PutMapping("/holdings/{id}") @Transactional public ApiResponse<HoldingRow> updateHolding(@PathVariable Long id,@Valid @RequestBody HoldingRequest b,HttpServletRequest r){TbHold x=holdings.findById(id).filter(v->"N".equals(v.getDeleteYn())).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));holdings.findByAccount_AccountIdAndStock_StockIdAndDeleteYn(b.accountId(),b.stockId(),"N").filter(v->!v.getHoldingId().equals(id)).ifPresent(v->{throw new BusinessException(ErrorCode.DUPLICATE_RESOURCE);});apply(x,b);return ok(row(holdings.save(x)),r);}
 @GetMapping("/regular-buys") public ApiResponse<List<RegularBuyRow>> regularBuys(HttpServletRequest r){return ok(regularBuys.findAll().stream().filter(x->"N".equals(x.getDeleteYn())).map(this::row).toList(),r);}
 @PostMapping("/regular-buys") @Transactional public ApiResponse<RegularBuyRow> createRegularBuy(@Valid @RequestBody RegularBuyRequest b,HttpServletRequest r){if(regularBuys.findByAccount_AccountIdAndStock_StockIdAndDeleteYn(b.accountId(),b.stockId(),"N").isPresent())throw new BusinessException(ErrorCode.DUPLICATE_RESOURCE);TbRegBuy x=new TbRegBuy();apply(x,b);return ok(row(regularBuys.save(x)),r);}
 @PutMapping("/regular-buys/{accountType}/{stockCode}") @Transactional public ApiResponse<RegularBuyRow> updateRegularBuy(@PathVariable AccountType accountType,@PathVariable String stockCode,@Valid @RequestBody RegularBuyRequest b,HttpServletRequest r){TbRegBuy x=regularBuys.findById(new TbRegBuyId(accountType,stockCode)).filter(v->"N".equals(v.getDeleteYn())).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));TbAcct targetAccount=account(b.accountId());TbStk targetStock=stock(b.stockId());if(targetAccount.getAccountType()!=accountType||!targetStock.getStockCode().equals(stockCode))throw new BusinessException(ErrorCode.INVALID_REQUEST);apply(x,b);return ok(row(regularBuys.save(x)),r);}
 @GetMapping("/cash-reserves") public ApiResponse<List<CashReserveRow>> cashReserves(HttpServletRequest r){return ok(cashReserves.findAll().stream().map(this::row).toList(),r);}
 @PostMapping("/cash-reserves") @Transactional public ApiResponse<CashReserveRow> createCashReserve(@Valid @RequestBody CashReserveRequest b,HttpServletRequest r){if(cashReserves.findByAccount_AccountId(b.accountId()).isPresent())throw new BusinessException(ErrorCode.DUPLICATE_RESOURCE);TbCashRsv x=new TbCashRsv();apply(x,b);return ok(row(cashReserves.save(x)),r);}
 @PutMapping("/cash-reserves/{id}") @Transactional public ApiResponse<CashReserveRow> updateCashReserve(@PathVariable Long id,@Valid @RequestBody CashReserveRequest b,HttpServletRequest r){TbCashRsv x=cashReserves.findById(id).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));cashReserves.findByAccount_AccountId(b.accountId()).filter(v->!v.getCashReserveId().equals(id)).ifPresent(v->{throw new BusinessException(ErrorCode.DUPLICATE_RESOURCE);});apply(x,b);return ok(row(cashReserves.save(x)),r);}
 private TbAcct account(Long id){return accounts.findById(id).filter(x->"N".equals(x.getDeleteYn())).orElseThrow(()->new BusinessException(ErrorCode.ACCOUNT_NOT_FOUND));} private TbStk stock(Long id){return stocks.findById(id).filter(x->"N".equals(x.getDeleteYn())).orElseThrow(()->new BusinessException(ErrorCode.STOCK_NOT_FOUND));}
 private void apply(TbHold x,HoldingRequest b){x.setAccount(account(b.accountId()));x.setStock(stock(b.stockId()));x.setHoldingQuantity(b.holdingQuantity());x.setAveragePrice(b.averagePrice());x.setExchangeRate(b.exchangeRate());x.setTargetWeight(b.targetWeight());x.setHoldingStatus(b.holdingStatus());x.setMemo(b.memo());x.setUseYn(nvl(b.useYn(),"Y"));x.setDeleteYn("N");}
 private void apply(TbRegBuy x,RegularBuyRequest b){TbAcct a=account(b.accountId());TbStk s=stock(b.stockId());x.setAccountType(a.getAccountType());x.setStockCode(s.getStockCode());x.setLegacyStockName(s.getStockName());x.setAccount(a);x.setStock(s);x.setBuyCycle(b.buyCycle());x.setBuyDayCode(b.buyCycle()==BuyCycle.WEEKLY?b.buyDayCode():null);x.setBuyDayNumber(null);x.setBuyDayNumbers(b.buyCycle()==BuyCycle.MONTHLY?b.buyDayNumbers():null);applyLegacySchedule(x,b);x.setBuyBasis(b.buyBasis());x.setMinimumBuyAmount(b.minimumBuyAmount());x.setMaximumBuyAmount(b.maximumBuyAmount());x.setBaseBuyQuantity(b.baseBuyQuantity());x.setBuyQuantity(b.buyQuantity());x.setMaximumMultiplier(b.maximumMultiplier());RegularBuyStatus status=b.buyStatus();String userPause=nvl(b.userPauseYn(),"N");if(status==RegularBuyStatus.STOPPED)userPause="N";else if("Y".equals(userPause))status=RegularBuyStatus.PAUSED;x.setBuyStatus(status);x.setPauseReason(b.pauseReason());x.setUserPauseYn(userPause);x.setAutoCalculateYn(nvl(b.autoCalculateYn(),"Y"));x.setUseYn(status==RegularBuyStatus.STOPPED?"N":"Y");x.setLegacyActiveYn(status==RegularBuyStatus.ACTIVE?"Y":"N");x.setDeleteYn("N");}
 private void applyLegacySchedule(TbRegBuy x,RegularBuyRequest b){x.setLegacyWeekDays(null);x.setLegacyMonthDay(null);if(b.buyCycle()==BuyCycle.WEEKLY){x.setLegacyCycleType("WEEKLY");x.setLegacyWeekDays(b.buyDayCode());return;}if(b.buyCycle()==BuyCycle.MONTHLY&&b.buyDayNumbers()!=null&&!b.buyDayNumbers().contains(",")){x.setLegacyCycleType("MONTHLY");x.setLegacyMonthDay(Integer.valueOf(b.buyDayNumbers()));return;}x.setLegacyCycleType(b.buyCycle()==BuyCycle.DAILY?"DAILY":"MANUAL");}
 private void apply(TbCashRsv x,CashReserveRequest b){x.setAccount(account(b.accountId()));x.setReserveAmount(b.reserveAmount());x.setAccumulatedAmount(b.accumulatedAmount());x.setUsedAmount(b.usedAmount());x.setLastTransactionDate(b.lastTransactionDate());}
 private HoldingRow row(TbHold x){return new HoldingRow(x.getHoldingId(),x.getAccount().getAccountId(),x.getAccount().getAccountType(),x.getStock().getStockId(),x.getStock().getStockCode(),x.getStock().getStockName(),x.getHoldingQuantity(),x.getAveragePrice(),x.getCurrentPrice(),x.getExchangeRate(),x.getEvaluationAmount(),x.getProfitLossRate(),x.getTargetWeight(),x.getHoldingStatus(),x.getMemo(),x.getUseYn());}
 private RegularBuyRow row(TbRegBuy x){return new RegularBuyRow(x.getAccountType()+"/"+x.getStockCode(),x.getAccount().getAccountId(),x.getAccount().getAccountType(),x.getStock().getStockId(),x.getStock().getStockCode(),x.getStock().getStockName(),x.getBuyCycle(),x.getBuyDayCode(),x.getBuyDayNumber(),x.getBuyDayNumbers(),x.getBuyBasis(),x.getMinimumBuyAmount(),x.getMaximumBuyAmount(),x.getBaseBuyQuantity(),x.getBuyQuantity(),x.getMaximumMultiplier(),x.getRecommendedBuyAmount(),x.getBuyStatus(),x.getPauseReason(),x.getUserPauseYn(),x.getAutoCalculateYn(),x.getUseYn());}
 private CashReserveRow row(TbCashRsv x){BigDecimal available=x.getAccumulatedAmount().subtract(x.getUsedAmount());return new CashReserveRow(x.getCashReserveId(),x.getAccount().getAccountId(),x.getAccount().getAccountType(),x.getReserveAmount(),x.getAccumulatedAmount(),x.getUsedAmount(),available,x.getLastTransactionDate(),x.getVersion());}
 private String nvl(String v,String d){return v==null?d:v;} private <T> ApiResponse<T> ok(T d,HttpServletRequest r){return ApiResponse.success(d,TraceIdUtils.resolve(r));}
}

