CREATE TABLE "TB_KRX_BF_JOB" (
    "ID" UUID PRIMARY KEY,
    "FROM_DT" DATE NOT NULL,
    "TO_DT" DATE NOT NULL,
    "ST" VARCHAR(30) NOT NULL,
    "DATA_CDS" VARCHAR(1000) NOT NULL,
    "REQ_INTERVAL_MS" BIGINT NOT NULL DEFAULT 250,
    "TOT_DAY_CNT" INTEGER NOT NULL DEFAULT 0,
    "SUCCESS_DAY_CNT" INTEGER NOT NULL DEFAULT 0,
    "FAILED_DAY_CNT" INTEGER NOT NULL DEFAULT 0,
    "SKIP_DAY_CNT" INTEGER NOT NULL DEFAULT 0,
    "PENDING_DAY_CNT" INTEGER NOT NULL DEFAULT 0,
    "CURR_DT" DATE,
    "ERR_MSG" VARCHAR(4000),
    "REG_DT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "START_DT" TIMESTAMP,
    "END_DT" TIMESTAMP,
    "UPD_DT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_TB_KRX_BF_JOB_01" CHECK ("FROM_DT" <= "TO_DT"),
    CONSTRAINT "CK_TB_KRX_BF_JOB_02" CHECK ("REQ_INTERVAL_MS" BETWEEN 0 AND 60000),
    CONSTRAINT "CK_TB_KRX_BF_JOB_03" CHECK (
        "ST" IN ('QUEUED','RUNNING','PAUSE_REQUESTED','PAUSED','CANCEL_REQUESTED',
                 'CANCELLED','COMPLETED','COMPLETED_WITH_ERRORS','FAILED'))
);

CREATE TABLE "TB_KRX_BF_DAY" (
    "ID" BIGSERIAL PRIMARY KEY,
    "BF_JOB_ID" UUID NOT NULL REFERENCES "TB_KRX_BF_JOB"("ID") ON DELETE CASCADE,
    "BASE_DT" DATE NOT NULL,
    "ST" VARCHAR(30) NOT NULL,
    "SKIP_RSN" VARCHAR(200),
    "CLCT_JOB_ID" UUID REFERENCES "TB_KRX_CLCT_JOB"("ID"),
    "RETRY_DATA_CDS" VARCHAR(1000),
    "ATTEMPT_CNT" INTEGER NOT NULL DEFAULT 0,
    "ERR_MSG" VARCHAR(4000),
    "START_DT" TIMESTAMP,
    "END_DT" TIMESTAMP,
    "UPD_DT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UK_TB_KRX_BF_DAY_01" UNIQUE ("BF_JOB_ID", "BASE_DT"),
    CONSTRAINT "CK_TB_KRX_BF_DAY_01" CHECK (
        "ST" IN ('PENDING','RUNNING','SUCCESS','FAILED','SKIPPED','CANCELLED'))
);

CREATE INDEX "IX_TB_KRX_BF_JOB_01"
    ON "TB_KRX_BF_JOB"("REG_DT" DESC);

CREATE INDEX "IX_TB_KRX_BF_JOB_02"
    ON "TB_KRX_BF_JOB"("FROM_DT", "TO_DT", "ST");

CREATE INDEX "IX_TB_KRX_BF_DAY_01"
    ON "TB_KRX_BF_DAY"("BF_JOB_ID", "ST", "BASE_DT");

CREATE UNIQUE INDEX "UX_TB_KRX_BF_JOB_ACTIVE"
    ON "TB_KRX_BF_JOB"("FROM_DT", "TO_DT", "DATA_CDS")
    WHERE "ST" IN ('QUEUED','RUNNING','PAUSE_REQUESTED','PAUSED','CANCEL_REQUESTED');

CREATE VIEW tb_krx_bf_job AS
SELECT
    "ID" id,
    "FROM_DT" from_date,
    "TO_DT" to_date,
    "ST" status,
    "DATA_CDS" dataset_codes,
    "REQ_INTERVAL_MS" request_interval_ms,
    "TOT_DAY_CNT" total_day_count,
    "SUCCESS_DAY_CNT" success_day_count,
    "FAILED_DAY_CNT" failed_day_count,
    "SKIP_DAY_CNT" skipped_day_count,
    "PENDING_DAY_CNT" pending_day_count,
    "CURR_DT" current_date,
    "ERR_MSG" error_message,
    "REG_DT" created_at,
    "START_DT" started_at,
    "END_DT" completed_at,
    "UPD_DT" updated_at
FROM "TB_KRX_BF_JOB";

CREATE VIEW tb_krx_bf_day AS
SELECT
    "ID" id,
    "BF_JOB_ID" backfill_job_id,
    "BASE_DT" base_date,
    "ST" status,
    "SKIP_RSN" skip_reason,
    "CLCT_JOB_ID" collection_job_id,
    "RETRY_DATA_CDS" retry_dataset_codes,
    "ATTEMPT_CNT" attempt_count,
    "ERR_MSG" error_message,
    "START_DT" started_at,
    "END_DT" completed_at,
    "UPD_DT" updated_at
FROM "TB_KRX_BF_DAY";

COMMENT ON TABLE "TB_KRX_BF_JOB" IS 'KRX 기간 백필 상위 작업';
COMMENT ON TABLE "TB_KRX_BF_DAY" IS 'KRX 기간 백필 날짜별 하위 작업';
COMMENT ON COLUMN "TB_KRX_BF_JOB"."DATA_CDS" IS '정렬된 KRX Dataset 코드 CSV';
COMMENT ON COLUMN "TB_KRX_BF_JOB"."REQ_INTERVAL_MS" IS '백필 전체 KRX 요청 사이의 최소 간격(ms)';
COMMENT ON COLUMN "TB_KRX_BF_DAY"."RETRY_DATA_CDS" IS 'Dataset 범위 재처리 시 실패 Dataset 코드 CSV';
