CREATE TABLE "TB_KRX_DRV_IDX_DAY" (
  "BASE_DT" DATE NOT NULL, "IDX_CLSS" VARCHAR(100) NOT NULL, "IDX_NM" VARCHAR(200) NOT NULL,
  "CLS_IDX" NUMERIC(20,6), "CHG_IDX" NUMERIC(20,6), "CHG_RT" NUMERIC(12,6),
  "OPEN_IDX" NUMERIC(20,6), "HIGH_IDX" NUMERIC(20,6), "LOW_IDX" NUMERIC(20,6),
  "TRD_VOL" NUMERIC(30,4), "TRD_AMT" NUMERIC(30,4), "RAW_PAYLOAD" JSONB NOT NULL,
  "REG_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "MOD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_KRX_DRV_IDX_DAY" PRIMARY KEY ("BASE_DT", "IDX_CLSS", "IDX_NM")
);
CREATE INDEX "IX_KRX_DRV_IDX_NM_DT" ON "TB_KRX_DRV_IDX_DAY" ("IDX_NM", "BASE_DT" DESC);

CREATE TABLE "TB_KRX_FUT_DAY" (
  "BASE_DT" DATE NOT NULL, "ISU_CD" VARCHAR(50) NOT NULL, "ISU_NM" VARCHAR(200),
  "EXPIRATION_CD" VARCHAR(20), "CLS_PRC" NUMERIC(20,6), "OPEN_PRC" NUMERIC(20,6),
  "HIGH_PRC" NUMERIC(20,6), "LOW_PRC" NUMERIC(20,6), "TRD_VOL" NUMERIC(30,4),
  "TRD_AMT" NUMERIC(30,4), "OPEN_INT" NUMERIC(30,4), "RAW_PAYLOAD" JSONB NOT NULL,
  "REG_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "MOD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_KRX_FUT_DAY" PRIMARY KEY ("BASE_DT", "ISU_CD")
);
CREATE INDEX "IX_KRX_FUT_EXP_DT" ON "TB_KRX_FUT_DAY" ("EXPIRATION_CD", "BASE_DT" DESC);
