-- 파생상품 일별 데이터에 자연키를 이관한다.
ALTER TABLE "TB_DERIV_DAY" ADD COLUMN "ISU_CD" VARCHAR(50);
UPDATE "TB_DERIV_DAY" d SET "ISU_CD"=m."ISU_CD"
FROM "TB_DERIV" m WHERE m."DERIV_ID"=d."DERIV_ID";
ALTER TABLE "TB_DERIV_DAY" ALTER COLUMN "ISU_CD" SET NOT NULL;

ALTER TABLE "TB_DERIV_DAY" DROP CONSTRAINT "TB_DERIV_DAY_DERIV_ID_fkey";
ALTER TABLE "TB_DERIV_DAY" DROP CONSTRAINT "TB_DERIV_DAY_pkey";
ALTER TABLE "TB_DERIV_DAY" DROP CONSTRAINT "UK_TB_DERIV_DAY_01";
DROP INDEX "IDX_TB_DERIV_DAY_01";
ALTER TABLE "TB_DERIV_DAY" DROP COLUMN "DERIV_DAY_ID";
ALTER TABLE "TB_DERIV_DAY" DROP COLUMN "DERIV_ID";

ALTER TABLE "TB_DERIV" DROP CONSTRAINT "TB_DERIV_pkey";
ALTER TABLE "TB_DERIV" DROP CONSTRAINT "UK_TB_DERIV_01";
ALTER TABLE "TB_DERIV" DROP COLUMN "DERIV_ID";
ALTER TABLE "TB_DERIV" ADD CONSTRAINT "PK_TB_DERIV" PRIMARY KEY ("ISU_CD");

ALTER TABLE "TB_DERIV_DAY"
  ADD CONSTRAINT "PK_TB_DERIV_DAY" PRIMARY KEY ("ISU_CD","TRADE_DT"),
  ADD CONSTRAINT "FK_TB_DERIV_DAY_01" FOREIGN KEY ("ISU_CD")
    REFERENCES "TB_DERIV"("ISU_CD") ON UPDATE CASCADE ON DELETE RESTRICT;
CREATE INDEX "IDX_TB_DERIV_DAY_01" ON "TB_DERIV_DAY" ("ISU_CD","TRADE_DT" DESC);

-- 개별채권 일별 데이터에 자연키를 이관한다.
ALTER TABLE "TB_BOND_TRD_DAY" ADD COLUMN "ISU_CD" VARCHAR(50);
UPDATE "TB_BOND_TRD_DAY" d SET "ISU_CD"=m."ISU_CD"
FROM "TB_BOND" m WHERE m."BOND_ID"=d."BOND_ID";
ALTER TABLE "TB_BOND_TRD_DAY" ALTER COLUMN "ISU_CD" SET NOT NULL;

ALTER TABLE "TB_BOND_TRD_DAY" DROP CONSTRAINT "TB_BOND_TRD_DAY_BOND_ID_fkey";
ALTER TABLE "TB_BOND_TRD_DAY" DROP CONSTRAINT "TB_BOND_TRD_DAY_pkey";
ALTER TABLE "TB_BOND_TRD_DAY" DROP CONSTRAINT "UK_TB_BOND_TRD_DAY_01";
DROP INDEX "IDX_TB_BOND_TRD_DAY_01";
ALTER TABLE "TB_BOND_TRD_DAY" DROP COLUMN "BOND_TRD_DAY_ID";
ALTER TABLE "TB_BOND_TRD_DAY" DROP COLUMN "BOND_ID";

ALTER TABLE "TB_BOND" DROP CONSTRAINT "TB_BOND_pkey";
ALTER TABLE "TB_BOND" DROP CONSTRAINT "UK_TB_BOND_01";
ALTER TABLE "TB_BOND" DROP COLUMN "BOND_ID";
ALTER TABLE "TB_BOND" ADD CONSTRAINT "PK_TB_BOND" PRIMARY KEY ("ISU_CD");

ALTER TABLE "TB_BOND_TRD_DAY"
  ADD CONSTRAINT "PK_TB_BOND_TRD_DAY" PRIMARY KEY ("ISU_CD","TRADE_DT"),
  ADD CONSTRAINT "FK_TB_BOND_TRD_DAY_01" FOREIGN KEY ("ISU_CD")
    REFERENCES "TB_BOND"("ISU_CD") ON UPDATE CASCADE ON DELETE RESTRICT;
CREATE INDEX "IDX_TB_BOND_TRD_DAY_01" ON "TB_BOND_TRD_DAY" ("ISU_CD","TRADE_DT" DESC);

COMMENT ON COLUMN "TB_DERIV"."ISU_CD" IS '파생상품 종목코드이자 기본키';
COMMENT ON COLUMN "TB_DERIV_DAY"."ISU_CD" IS '파생상품 종목코드이자 일별 복합 기본키';
COMMENT ON COLUMN "TB_BOND"."ISU_CD" IS '채권 종목코드이자 기본키';
COMMENT ON COLUMN "TB_BOND_TRD_DAY"."ISU_CD" IS '채권 종목코드이자 일별 복합 기본키';
