-- 시세/지수/FRED 금리 데이터의 업무 식별자를 PK/FK로 사용한다.
-- KRX 응답의 ISU_CD는 TB_PRC_DAY.STK_CD로 정규화되어 저장된다.

DROP VIEW IF EXISTS tb_prc_day;

ALTER TABLE "TB_PRC_DAY" DROP CONSTRAINT IF EXISTS "PK_TB_PRC_DAY";
ALTER TABLE "TB_PRC_DAY" DROP CONSTRAINT IF EXISTS "UK_TB_PRC_DAY_LEGACY";
ALTER TABLE "TB_PRC_DAY" DROP CONSTRAINT IF EXISTS "FK_TB_PRC_DAY_STK";
ALTER TABLE "TB_PRC_DAY" DROP COLUMN "PRC_DAY_ID";
ALTER TABLE "TB_PRC_DAY"
  ADD CONSTRAINT "PK_TB_PRC_DAY" PRIMARY KEY ("STK_CD", "TRADE_DT"),
  ADD CONSTRAINT "FK_TB_PRC_DAY_STK_CD" FOREIGN KEY ("STK_CD") REFERENCES "TB_STK"("STK_CD");

CREATE VIEW tb_prc_day AS
SELECT "STK_CD" symbol,"TRADE_DT" trading_day,"OPEN_PRC" open_price,
       "HIGH_PRC" high_price,"LOW_PRC" low_price,"CLS_PRC" close_price,
       "ADJ_CLS_PRC" adjusted_close,"VOL" volume,"PRVDR" provider,
       "REG_DT" created_at,"MOD_DT" updated_at,
       CASE WHEN "MKT_CD"='US' THEN 'OVERSEAS' ELSE 'DOMESTIC' END market_scope
FROM "TB_PRC_DAY";

ALTER TABLE "TB_IDX_DAY" ADD COLUMN "IDX_CD" VARCHAR(30);
UPDATE "TB_IDX_DAY" d SET "IDX_CD"=i."IDX_CD" FROM "TB_IDX" i WHERE i."IDX_ID"=d."IDX_ID";
ALTER TABLE "TB_STK" ADD COLUMN "BASE_IDX_CD" VARCHAR(30);
UPDATE "TB_STK" s SET "BASE_IDX_CD"=i."IDX_CD" FROM "TB_IDX" i WHERE i."IDX_ID"=s."BASE_IDX_ID";
ALTER TABLE "TB_MKT_SNAP" ADD COLUMN "MAIN_IDX_CD" VARCHAR(30), ADD COLUMN "SUB_IDX_CD" VARCHAR(30);
UPDATE "TB_MKT_SNAP" s SET "MAIN_IDX_CD"=m."IDX_CD" FROM "TB_IDX" m WHERE m."IDX_ID"=s."MAIN_IDX_ID";
UPDATE "TB_MKT_SNAP" s SET "SUB_IDX_CD"=i."IDX_CD" FROM "TB_IDX" i WHERE i."IDX_ID"=s."SUB_IDX_ID";

ALTER TABLE "TB_IDX_DAY" DROP CONSTRAINT IF EXISTS "FK_TB_IDX_DAY_01";
ALTER TABLE "TB_IDX_DAY" DROP CONSTRAINT IF EXISTS "UK_TB_IDX_DAY_01";
ALTER TABLE "TB_IDX_DAY" DROP CONSTRAINT IF EXISTS "PK_TB_IDX_DAY";
ALTER TABLE "TB_STK" DROP CONSTRAINT IF EXISTS "FK_TB_STK_01";
ALTER TABLE "TB_MKT_SNAP" DROP CONSTRAINT IF EXISTS "FK_TB_MKT_SNAP_01";
ALTER TABLE "TB_MKT_SNAP" DROP CONSTRAINT IF EXISTS "FK_TB_MKT_SNAP_02";
DROP INDEX IF EXISTS "IDX_TB_IDX_DAY_01";
DROP INDEX IF EXISTS "IDX_TB_STK_03";

ALTER TABLE "TB_IDX_DAY" ALTER COLUMN "IDX_CD" SET NOT NULL;
ALTER TABLE "TB_IDX_DAY" DROP COLUMN "IDX_DAY_ID", DROP COLUMN "IDX_ID";
ALTER TABLE "TB_STK" DROP COLUMN "BASE_IDX_ID";
ALTER TABLE "TB_MKT_SNAP" DROP COLUMN "MAIN_IDX_ID", DROP COLUMN "SUB_IDX_ID";
ALTER TABLE "TB_IDX" DROP CONSTRAINT IF EXISTS "UK_TB_IDX_01";
ALTER TABLE "TB_IDX" DROP CONSTRAINT IF EXISTS "PK_TB_IDX";
ALTER TABLE "TB_IDX" DROP COLUMN "IDX_ID";
ALTER TABLE "TB_IDX" ADD CONSTRAINT "PK_TB_IDX" PRIMARY KEY ("IDX_CD");
ALTER TABLE "TB_IDX_DAY"
  ADD CONSTRAINT "PK_TB_IDX_DAY" PRIMARY KEY ("IDX_CD", "TRADE_DT"),
  ADD CONSTRAINT "FK_TB_IDX_DAY_01" FOREIGN KEY ("IDX_CD") REFERENCES "TB_IDX"("IDX_CD");
ALTER TABLE "TB_STK" ADD CONSTRAINT "FK_TB_STK_01" FOREIGN KEY ("BASE_IDX_CD") REFERENCES "TB_IDX"("IDX_CD");
ALTER TABLE "TB_MKT_SNAP"
  ADD CONSTRAINT "FK_TB_MKT_SNAP_01" FOREIGN KEY ("MAIN_IDX_CD") REFERENCES "TB_IDX"("IDX_CD"),
  ADD CONSTRAINT "FK_TB_MKT_SNAP_02" FOREIGN KEY ("SUB_IDX_CD") REFERENCES "TB_IDX"("IDX_CD");
CREATE INDEX "IDX_TB_IDX_DAY_01" ON "TB_IDX_DAY"("IDX_CD","TRADE_DT" DESC);
CREATE INDEX "IDX_TB_STK_03" ON "TB_STK"("BASE_IDX_CD");

ALTER TABLE "TB_BOND_DAY" RENAME TO "TB_FRED_BOND_DAY";
ALTER TABLE "TB_FRED_BOND_DAY" DROP CONSTRAINT IF EXISTS "PK_TB_BOND_DAY";
ALTER TABLE "TB_FRED_BOND_DAY" DROP CONSTRAINT IF EXISTS "UK_TB_BOND_DAY_01";
ALTER TABLE "TB_FRED_BOND_DAY" DROP COLUMN "BOND_DAY_ID";
ALTER TABLE "TB_FRED_BOND_DAY" ADD CONSTRAINT "PK_TB_FRED_BOND_DAY" PRIMARY KEY ("BOND_CD","BASE_DT");
ALTER INDEX IF EXISTS "IDX_TB_BOND_DAY_01" RENAME TO "IDX_TB_FRED_BOND_DAY_01";
ALTER INDEX IF EXISTS "IDX_TB_BOND_DAY_02" RENAME TO "IDX_TB_FRED_BOND_DAY_02";

COMMENT ON COLUMN "TB_PRC_DAY"."STK_CD" IS '종목코드(KRX ISU_CD 정규화 값, PK/FK)';
COMMENT ON COLUMN "TB_IDX"."IDX_CD" IS '기준지수 코드(PK)';
COMMENT ON COLUMN "TB_IDX_DAY"."IDX_CD" IS '기준지수 코드(PK/FK)';
COMMENT ON COLUMN "TB_STK"."BASE_IDX_CD" IS '기준지수 코드(FK)';
COMMENT ON COLUMN "TB_MKT_SNAP"."MAIN_IDX_CD" IS '대표 기준지수 코드(FK)';
COMMENT ON COLUMN "TB_MKT_SNAP"."SUB_IDX_CD" IS '보조 기준지수 코드(FK)';
COMMENT ON TABLE "TB_FRED_BOND_DAY" IS 'FRED 거시 시계열 중 채권금리 일별 데이터';
COMMENT ON COLUMN "TB_FRED_BOND_DAY"."BOND_CD" IS 'FRED 시계열 코드(PK)';
COMMENT ON COLUMN "TB_FRED_BOND_DAY"."BASE_DT" IS 'FRED 관측 기준일(PK)';
