CREATE TABLE "TB_KOFIA_RAW_RSP" (
  "RAW_RSP_ID" UUID PRIMARY KEY,
  "JOB_ID" UUID,
  "DATASET_CD" VARCHAR(60) NOT NULL,
  "REQ_FROM_DT" DATE NOT NULL,
  "REQ_TO_DT" DATE NOT NULL,
  "HTTP_STS" INTEGER NOT NULL,
  "ROW_CNT" INTEGER NOT NULL DEFAULT 0,
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "PAYLOAD" JSONB NOT NULL,
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "IX_KOFIA_RAW_RSP_DATASET_DT"
  ON "TB_KOFIA_RAW_RSP" ("DATASET_CD", "REQ_FROM_DT", "REQ_TO_DT");

CREATE TABLE "TB_KOFIA_DATA_ROW" (
  "DATASET_CD" VARCHAR(60) NOT NULL,
  "BASE_DT" DATE NOT NULL,
  "ROW_KEY" VARCHAR(200) NOT NULL,
  "PAYLOAD" JSONB NOT NULL,
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "FIRST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("DATASET_CD", "BASE_DT", "ROW_KEY")
);

CREATE TABLE "TB_KOFIA_CRDT_BAL_DAY" (
  "BASE_DT" DATE PRIMARY KEY,
  "CRDT_LOAN_TOT_AMT" NUMERIC(24, 4),
  "KOSPI_CRDT_LOAN_AMT" NUMERIC(24, 4),
  "KOSDAQ_CRDT_LOAN_AMT" NUMERIC(24, 4),
  "STK_LOAN_TOT_AMT" NUMERIC(24, 4),
  "KOSPI_STK_LOAN_AMT" NUMERIC(24, 4),
  "KOSDAQ_STK_LOAN_AMT" NUMERIC(24, 4),
  "ETC_STK_LOAN_AMT" NUMERIC(24, 4),
  "SECU_COLLATERAL_LOAN_AMT" NUMERIC(24, 4),
  "UNIT_CD" VARCHAR(20) NOT NULL DEFAULT 'MILLION_KRW',
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "TB_KOFIA_CLCT_JOB" (
  "JOB_ID" UUID PRIMARY KEY,
  "FROM_DT" DATE NOT NULL,
  "TO_DT" DATE NOT NULL,
  "DATASET_CDS" VARCHAR(1000) NOT NULL,
  "STS" VARCHAR(30) NOT NULL,
  "TOTAL_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "SUCCESS_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "FAILED_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "ERROR_MSG" VARCHAR(4000),
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "START_DTTM" TIMESTAMP,
  "COMPLETE_DTTM" TIMESTAMP
);

CREATE UNIQUE INDEX "UX_KOFIA_CLCT_JOB_ACTIVE_RANGE"
  ON "TB_KOFIA_CLCT_JOB" ("FROM_DT", "TO_DT", "DATASET_CDS")
  WHERE "STS" IN ('QUEUED', 'RUNNING');

CREATE TABLE "TB_KOFIA_CLCT_JOB_ITEM" (
  "ITEM_ID" BIGSERIAL PRIMARY KEY,
  "JOB_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CLCT_JOB"("JOB_ID") ON DELETE CASCADE,
  "DATASET_CD" VARCHAR(60) NOT NULL,
  "FROM_DT" DATE NOT NULL,
  "TO_DT" DATE NOT NULL,
  "STS" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  "RECEIVED_CNT" INTEGER NOT NULL DEFAULT 0,
  "STORED_CNT" INTEGER NOT NULL DEFAULT 0,
  "ERROR_MSG" VARCHAR(4000),
  "START_DTTM" TIMESTAMP,
  "COMPLETE_DTTM" TIMESTAMP,
  UNIQUE ("JOB_ID", "DATASET_CD", "FROM_DT", "TO_DT")
);

COMMENT ON TABLE "TB_KOFIA_RAW_RSP" IS 'KOFIA FreeSIS 원본 HTTP 응답';
COMMENT ON TABLE "TB_KOFIA_DATA_ROW" IS 'KOFIA Dataset별 원본 행';
COMMENT ON TABLE "TB_KOFIA_CRDT_BAL_DAY" IS '금융투자협회 신용공여 잔고 일별 정규화 데이터(금액 단위: 백만원)';
COMMENT ON TABLE "TB_KOFIA_CLCT_JOB" IS 'KOFIA 기간 수집 비동기 작업';
COMMENT ON TABLE "TB_KOFIA_CLCT_JOB_ITEM" IS 'KOFIA 기간 수집 Dataset 및 기간 조각별 실행 결과';
