CREATE TABLE "TB_EXT_CIRCUIT" (
  "CIRCUIT_KEY" VARCHAR(150) PRIMARY KEY,
  "STATE" VARCHAR(20) NOT NULL DEFAULT 'CLOSED',
  "FAILURE_CNT" INTEGER NOT NULL DEFAULT 0,
  "OPENED_AT" TIMESTAMP WITH TIME ZONE,
  "HALF_OPEN_IN_FLIGHT" BOOLEAN NOT NULL DEFAULT FALSE,
  "UPD_DTTM" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CK_TB_EXT_CIRCUIT_01" CHECK ("STATE" IN ('CLOSED','OPEN','HALF_OPEN')),
  CONSTRAINT "CK_TB_EXT_CIRCUIT_02" CHECK ("FAILURE_CNT" >= 0)
);

COMMENT ON TABLE "TB_EXT_CIRCUIT" IS '외부 공급자 Circuit Breaker 다중 인스턴스 공유 상태';
