UPDATE "TB_KRX_CLCT_JOB_ITEM" SET "ST"='DATA_RECEIVED' WHERE "ST"='SUCCESS' AND "RCV_CNT">0;
UPDATE "TB_KRX_CLCT_JOB_ITEM" i SET "ST"='MARKET_HOLIDAY'
WHERE "ST" IN ('SUCCESS','NO_DAILY_DATA') AND "RCV_CNT"=0
  AND EXTRACT(ISODOW FROM (SELECT j."BASE_DT" FROM "TB_KRX_CLCT_JOB" j WHERE j."ID"=i."JOB_ID")) IN (6,7);
UPDATE "TB_KRX_CLCT_JOB_ITEM" SET "ST"='NO_DATA_UNEXPECTED'
WHERE "ST" IN ('SUCCESS','NO_DAILY_DATA') AND "RCV_CNT"=0;

COMMENT ON COLUMN "TB_KRX_CLCT_JOB_ITEM"."ST" IS
  'DATA_RECEIVED, MARKET_HOLIDAY, NOT_PUBLISHED_YET, NO_DATA_UNEXPECTED, COLLECTION_FAILED, NOT_AUTHORIZED';
