CREATE TABLE "TB_KOFIA_SVC" (
  "SERVICE_ID" VARCHAR(60) PRIMARY KEY,
  "SERVICE_NM" VARCHAR(300) NOT NULL,
  "MENU_PATH" VARCHAR(1000),
  "PARENT_DIV_ID" VARCHAR(60),
  "MENU_DIV_ID" VARCHAR(60),
  "OBJ_NM" VARCHAR(100),
  "OUTPUT_FORM_NO" VARCHAR(60),
  "OUTPUT_SQL_KEY" VARCHAR(300),
  "POPULARITY_VAL" BIGINT,
  "FAVORITE_ROW_SEQ" INTEGER,
  "HEADER_META" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "SEARCH_META" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "UNIT_META" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "LATEST_DATE_META" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "META_HASH" VARCHAR(64) NOT NULL,
  "NORMALIZE_YN" CHAR(1) NOT NULL DEFAULT 'N',
  "USE_YN" CHAR(1) NOT NULL DEFAULT 'Y',
  "LAST_DISCOVER_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CK_KOFIA_SVC_01" CHECK ("NORMALIZE_YN" IN ('Y','N')),
  CONSTRAINT "CK_KOFIA_SVC_02" CHECK ("USE_YN" IN ('Y','N'))
);

CREATE TABLE "TB_KOFIA_SVC_RANK_HIS" (
  "SNAPSHOT_DT" DATE NOT NULL,
  "SERVICE_ID" VARCHAR(60) NOT NULL REFERENCES "TB_KOFIA_SVC"("SERVICE_ID"),
  "ROW_SEQ" INTEGER NOT NULL,
  "POPULARITY_VAL" BIGINT,
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("SNAPSHOT_DT", "SERVICE_ID")
);

ALTER TABLE "TB_KOFIA_DATA_ROW"
  ADD COLUMN "ROW_TYPE" VARCHAR(20) NOT NULL DEFAULT 'DATA',
  ADD COLUMN "ENTITY_CD" VARCHAR(100),
  ADD COLUMN "ENTITY_NM" VARCHAR(300),
  ADD COLUMN "METRIC_SCOPE_CD" VARCHAR(100),
  ADD COLUMN "REQ_PARAMS" JSONB,
  ADD CONSTRAINT "CK_KOFIA_DATA_ROW_01"
    CHECK ("ROW_TYPE" IN ('DATA','TOTAL','AVERAGE','SUBTOTAL','OTHER'));

CREATE TABLE "TB_KOFIA_SEC_LEND_DAY" (
  "BASE_DT" DATE NOT NULL,
  "ITEM_CD" VARCHAR(40) NOT NULL,
  "ITEM_NM" VARCHAR(200) NOT NULL,
  "CONTRACT_QTY" NUMERIC(24,0),
  "REPAY_QTY" NUMERIC(24,0),
  "BALANCE_QTY" NUMERIC(24,0),
  "BALANCE_MKT_AMT" NUMERIC(24,4),
  "AMT_UNIT_CD" VARCHAR(20) NOT NULL DEFAULT 'MILLION_KRW',
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("BASE_DT", "ITEM_CD"),
  CONSTRAINT "CK_KOFIA_SEC_LEND_01" CHECK ("DATA_STS" IN ('FRESH','STALE','MISSING','PARTIAL','ERROR'))
);

CREATE TABLE "TB_KOFIA_MKT_FUND_DAY" (
  "BASE_DT" DATE PRIMARY KEY,
  "INVESTOR_DEPOSIT_AMT" NUMERIC(24,4),
  "DERIV_DEPOSIT_AMT" NUMERIC(24,4),
  "CUSTOMER_RP_BALANCE_AMT" NUMERIC(24,4),
  "RECEIVABLE_AMT" NUMERIC(24,4),
  "FORCED_LIQUIDATION_AMT" NUMERIC(24,4),
  "FORCED_LIQUIDATION_RT" NUMERIC(12,6),
  "UNIT_CD" VARCHAR(20) NOT NULL DEFAULT 'MILLION_KRW',
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CK_KOFIA_MKT_FUND_01" CHECK ("DATA_STS" IN ('FRESH','STALE','MISSING','PARTIAL','ERROR'))
);

COMMENT ON TABLE "TB_KOFIA_SVC" IS 'FreeSIS 즐겨찾는 통계 서비스 및 실행 메타데이터 카탈로그';
COMMENT ON TABLE "TB_KOFIA_SVC_RANK_HIS" IS 'FreeSIS 즐겨찾는 통계 일별 순위 스냅샷';
COMMENT ON TABLE "TB_KOFIA_SEC_LEND_DAY" IS '금융투자협회 대차거래 일별 정규화 데이터';
COMMENT ON TABLE "TB_KOFIA_MKT_FUND_DAY" IS '금융투자협회 증시자금 일별 정규화 데이터';
