INSERT INTO "TB_KOFIA_DATA_ROW"
    ("DATASET_CD", "BASE_DT", "ROW_KEY", "PAYLOAD", "RAW_HASH", "FIRST_COLLECT_DTTM",
     "LAST_COLLECT_DTTM", "ROW_TYPE", "ENTITY_CD", "ENTITY_NM", "METRIC_SCOPE_CD", "REQ_PARAMS")
SELECT "DATASET_CD", "BASE_DT", TO_CHAR("BASE_DT", 'YYYY-MM-DD'), "PAYLOAD", "RAW_HASH",
       "FIRST_COLLECT_DTTM", "LAST_COLLECT_DTTM", "ROW_TYPE", "ENTITY_CD", "ENTITY_NM",
       "METRIC_SCOPE_CD", "REQ_PARAMS"
  FROM "TB_KOFIA_DATA_ROW"
 WHERE "ROW_KEY" ~ '^[0-9]{8}$'
ON CONFLICT ("DATASET_CD", "BASE_DT", "ROW_KEY") DO UPDATE
SET "PAYLOAD" = EXCLUDED."PAYLOAD",
    "RAW_HASH" = EXCLUDED."RAW_HASH",
    "FIRST_COLLECT_DTTM" = LEAST("TB_KOFIA_DATA_ROW"."FIRST_COLLECT_DTTM", EXCLUDED."FIRST_COLLECT_DTTM"),
    "LAST_COLLECT_DTTM" = GREATEST("TB_KOFIA_DATA_ROW"."LAST_COLLECT_DTTM", EXCLUDED."LAST_COLLECT_DTTM"),
    "ROW_TYPE" = EXCLUDED."ROW_TYPE",
    "ENTITY_CD" = EXCLUDED."ENTITY_CD",
    "ENTITY_NM" = EXCLUDED."ENTITY_NM",
    "METRIC_SCOPE_CD" = EXCLUDED."METRIC_SCOPE_CD",
    "REQ_PARAMS" = EXCLUDED."REQ_PARAMS";

DELETE FROM "TB_KOFIA_DATA_ROW"
 WHERE "ROW_KEY" ~ '^[0-9]{8}$';
