DROP TRIGGER "TRG_EXCH_DAY_CORR" ON "TB_EXCH_DAY";

CREATE TRIGGER "TRG_EXCH_DAY_CORR"
AFTER UPDATE ON "TB_EXCH_DAY"
FOR EACH ROW
WHEN (OLD."EXCH_RT" IS DISTINCT FROM NEW."EXCH_RT")
EXECUTE FUNCTION "FN_AUDIT_PROVIDER_CORRECTION"('MARKET_DATA', 'EXCHANGE_DAY');

COMMENT ON TRIGGER "TRG_EXCH_DAY_CORR" ON "TB_EXCH_DAY"
IS 'Yahoo 원천 환율이 변경된 경우에만 정정 이력과 downstream 재계산 큐를 생성';
