ALTER TABLE "TB_EXCH_DAY" DROP CONSTRAINT "PK_TB_EXCH_DAY";
ALTER TABLE "TB_EXCH_DAY" DROP CONSTRAINT "UK_TB_EXCH_DAY_01";
ALTER TABLE "TB_EXCH_DAY" DROP COLUMN "EXCH_DAY_ID";

ALTER TABLE "TB_EXCH_DAY"
  ADD CONSTRAINT "PK_TB_EXCH_DAY"
  PRIMARY KEY ("BASE_DT", "BASE_CURR_CD", "QUOTE_CURR_CD");

COMMENT ON CONSTRAINT "PK_TB_EXCH_DAY" ON "TB_EXCH_DAY"
IS '환율 기준일과 기준·표시 통화쌍으로 식별하는 일별 환율 업무키';
