CREATE TABLE "TB_KOFIA_LOOKUP_RAW_RSP" (
  "RAW_RSP_ID" UUID PRIMARY KEY,
  "LOOKUP_TYP" VARCHAR(30) NOT NULL,
  "SCOPE_CD" VARCHAR(200) NOT NULL,
  "REQ_PARAMS" JSONB NOT NULL,
  "ROW_CNT" INTEGER NOT NULL,
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "PAYLOAD" JSONB NOT NULL,
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "IX_KOFIA_LOOKUP_RAW_RSP_01"
  ON "TB_KOFIA_LOOKUP_RAW_RSP"("LOOKUP_TYP", "SCOPE_CD", "COLLECT_DTTM");

CREATE TABLE "TB_KOFIA_BUSINESS_REF" (
  "MARKET_TYP_CD" CHAR(1) NOT NULL,
  "LARGE_CATEGORY_CD" VARCHAR(30) NOT NULL,
  "MIDDLE_CATEGORY_CD" VARCHAR(30) NOT NULL,
  "SMALL_CATEGORY_CD" VARCHAR(30) NOT NULL,
  "BUSINESS_SHORT_CD" VARCHAR(30) NOT NULL,
  "BUSINESS_NM" VARCHAR(300) NOT NULL,
  "SORT_SEQ" INTEGER,
  "PAYLOAD" JSONB NOT NULL,
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "USE_YN" CHAR(1) NOT NULL DEFAULT 'Y',
  "FIRST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("MARKET_TYP_CD", "LARGE_CATEGORY_CD", "MIDDLE_CATEGORY_CD",
    "SMALL_CATEGORY_CD", "BUSINESS_SHORT_CD"),
  CONSTRAINT "CK_KOFIA_BUSINESS_REF_01" CHECK ("MARKET_TYP_CD" IN ('1', '2')),
  CONSTRAINT "CK_KOFIA_BUSINESS_REF_02" CHECK ("USE_YN" IN ('Y', 'N'))
);

CREATE TABLE "TB_KOFIA_COMPANY_REF" (
  "TABLE_NM" VARCHAR(100) NOT NULL,
  "COMPANY_TYP_CD" CHAR(1) NOT NULL,
  "COMPANY_CD" VARCHAR(60) NOT NULL,
  "COMPANY_NM" VARCHAR(300) NOT NULL,
  "MIDDLE_CATEGORY_CD" VARCHAR(60),
  "PAYLOAD" JSONB NOT NULL,
  "RAW_HASH" VARCHAR(64) NOT NULL,
  "USE_YN" CHAR(1) NOT NULL DEFAULT 'Y',
  "FIRST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("TABLE_NM", "COMPANY_TYP_CD", "COMPANY_CD"),
  CONSTRAINT "CK_KOFIA_COMPANY_REF_01" CHECK ("COMPANY_TYP_CD" IN ('1', '2')),
  CONSTRAINT "CK_KOFIA_COMPANY_REF_02" CHECK ("USE_YN" IN ('Y', 'N'))
);

COMMENT ON TABLE "TB_KOFIA_LOOKUP_RAW_RSP" IS 'FreeSIS 업종 및 회사검색 원본 응답 이력';
COMMENT ON TABLE "TB_KOFIA_BUSINESS_REF" IS 'FreeSIS KOSPI/KOSDAQ 업종 검색 기준정보';
COMMENT ON TABLE "TB_KOFIA_COMPANY_REF" IS 'FreeSIS 테이블 및 회사구분별 운용회사/판매회사 기준정보';

INSERT INTO "TB_CD_DTL" (
  "CD_GRP", "CD_KEY", "CD_NM", "DESC", "DSP_ORD", "ACTV_YN"
)
VALUES
  ('T1100', '5', '투자신탁', 'Investment Trust', 10, 'Y'),
  ('T1100', '7', '투자조합', 'Investment Partnership', 20, 'Y'),
  ('T1100', 'A', '투자익명조합', 'Undisclosed Investment Association', 30, 'Y'),
  ('T1100', 'L', '투자유한회사', 'Investment Limited Company', 40, 'Y'),
  ('T1100', 'M', '투자회사', 'Investment Company', 50, 'Y'),
  ('T1100', 'P', '투자합자회사', 'Investment Limited Partnership Company', 60, 'Y'),
  ('T1100', 'V', '변액보험', 'Variable Insurance', 70, 'Y'),
  ('T1100', 'R', '투자유한책임회사', 'Investment Limited Liability Company', 70, 'Y'),
  ('T1102', '1', '공모', 'Public', 10, 'Y'),
  ('T1102', '2', '사모', 'Private', 20, 'Y'),
  ('T1111', '02', '주식형', 'Equity', 10, 'Y'),
  ('T1111', '03', '혼합주식형', 'Hybrid Equity', 20, 'Y'),
  ('T1111', '04', '혼합채권형', 'Hybrid Bond', 30, 'Y'),
  ('T1111', '01', '채권형', 'Bond', 40, 'Y'),
  ('T1111', '05', '단기금융', 'Short-term Finance', 50, 'Y'),
  ('T1111', '13', '투자계약', 'Investment Contract', 50, 'Y'),
  ('T1111', '06', '파생상품', 'Derivatives', 60, 'Y'),
  ('T1111', '07', '부동산', 'Real Estate', 70, 'Y'),
  ('T1111', '08', '실물', 'Real Asset', 80, 'Y'),
  ('T1111', '09', '재간접', 'Fund of funds', 90, 'Y'),
  ('T1111', '10', '변액보험', 'Variable Insurance', 100, 'Y'),
  ('T1111', '11', '특별자산', 'Special Asset', 110, 'Y'),
  ('T1111', '12', '혼합자산', 'Hybrid Asset', 120, 'Y'),
  ('T1111', '14', '기업성장', 'Corporate growth fund', 130, 'Y')
ON CONFLICT ("CD_GRP", "CD_KEY") DO UPDATE SET
  "CD_NM" = EXCLUDED."CD_NM",
  "DESC" = EXCLUDED."DESC",
  "DSP_ORD" = EXCLUDED."DSP_ORD",
  "ACTV_YN" = EXCLUDED."ACTV_YN",
  "MOD_DT" = CURRENT_TIMESTAMP;
