CREATE TABLE "TB_MKT_INT_DAY" (
  "MKT_CD" VARCHAR(20) NOT NULL,
  "BASE_DT" DATE NOT NULL,
  "TOTAL_STK_CNT" INTEGER NOT NULL,
  "ADV_STK_CNT" INTEGER NOT NULL,
  "DECL_STK_CNT" INTEGER NOT NULL,
  "UNCH_STK_CNT" INTEGER NOT NULL,
  "ADV_RATIO" NUMERIC(12,8) NOT NULL,
  "ABOVE_MA20_CNT" INTEGER NOT NULL,
  "MA20_ELIGIBLE_CNT" INTEGER NOT NULL,
  "ABOVE_MA20_RATIO" NUMERIC(12,8),
  "SIGNED_TURNOVER_RATIO" NUMERIC(12,8),
  "SOURCE_ROW_CNT" INTEGER NOT NULL,
  "CALC_VER" VARCHAR(30) NOT NULL,
  "SOURCE_DATA_HASH" VARCHAR(64) NOT NULL,
  "CRT_DTTM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MOD_DTTM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TB_MKT_INT_DAY" PRIMARY KEY ("MKT_CD", "BASE_DT"),
  CONSTRAINT "CK_TB_MKT_INT_DAY_01" CHECK (
    "TOTAL_STK_CNT">=0 AND "ADV_STK_CNT">=0 AND "DECL_STK_CNT">=0
    AND "UNCH_STK_CNT">=0 AND "ABOVE_MA20_CNT">=0 AND "MA20_ELIGIBLE_CNT">=0
    AND "SOURCE_ROW_CNT">=0),
  CONSTRAINT "CK_TB_MKT_INT_DAY_02" CHECK (
    "ADV_RATIO" BETWEEN 0 AND 100
    AND ("ABOVE_MA20_RATIO" IS NULL OR "ABOVE_MA20_RATIO" BETWEEN 0 AND 100)
    AND ("SIGNED_TURNOVER_RATIO" IS NULL OR "SIGNED_TURNOVER_RATIO" BETWEEN -100 AND 100))
);

CREATE INDEX "IX_TB_MKT_INT_DAY_01" ON "TB_MKT_INT_DAY" ("BASE_DT" DESC);

COMMENT ON TABLE "TB_MKT_INT_DAY" IS 'KRX KOSPI 전 종목 원천행에서 파생한 시장 내부강도 일별 이력';
COMMENT ON COLUMN "TB_MKT_INT_DAY"."ADV_RATIO" IS '상승 종목 수 / 유효 종목 수 * 100';
COMMENT ON COLUMN "TB_MKT_INT_DAY"."ABOVE_MA20_RATIO" IS '20 거래일 이력이 있는 종목 중 종가가 MA20을 상회하는 비율';
COMMENT ON COLUMN "TB_MKT_INT_DAY"."SIGNED_TURNOVER_RATIO" IS '등락 방향 부호를 적용한 거래대금 합 / 전체 거래대금 합 * 100';
