CREATE TABLE "TB_KOFIA_CO_FUND_FLOW_VARIANT" (
  "VARIANT_ID" UUID PRIMARY KEY,
  "STAGE_CD" VARCHAR(30) NOT NULL,
  "FUND_TYP_CD" VARCHAR(10) NOT NULL DEFAULT '*',
  "FUND_KIND_CD" VARCHAR(10) NOT NULL DEFAULT '*',
  "OFFERING_TYP_CD" VARCHAR(10) NOT NULL DEFAULT '*',
  "ETF_INCLUDE_YN" CHAR(1) NOT NULL,
  "PARAM_HASH" CHAR(64) NOT NULL,
  "COLLECT_YN" CHAR(1) NOT NULL DEFAULT 'Y',
  "FIRST_DATA_DT" DATE,
  "LAST_DATA_DT" DATE,
  "LAST_ROW_CNT" INTEGER NOT NULL DEFAULT 0,
  "EMPTY_STREAK_CNT" INTEGER NOT NULL DEFAULT 0,
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UX_KOFIA_CO_FUND_FLOW_VARIANT_01" UNIQUE
    ("FUND_TYP_CD", "FUND_KIND_CD", "OFFERING_TYP_CD", "ETF_INCLUDE_YN"),
  CONSTRAINT "UX_KOFIA_CO_FUND_FLOW_VARIANT_02" UNIQUE ("PARAM_HASH"),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_VARIANT_01" CHECK
    ("STAGE_CD" IN ('AGGREGATE','OFFERING','FUND_TYPE','FUND_KIND','VALID_VARIANT')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_VARIANT_02" CHECK
    ("OFFERING_TYP_CD" IN ('*','1','2')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_VARIANT_03" CHECK ("ETF_INCLUDE_YN" IN ('Y','N')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_VARIANT_04" CHECK ("COLLECT_YN" IN ('Y','N'))
);

CREATE INDEX "IX_KOFIA_CO_FUND_FLOW_VARIANT_01"
  ON "TB_KOFIA_CO_FUND_FLOW_VARIANT"("STAGE_CD", "COLLECT_YN");

CREATE TABLE "TB_KOFIA_CO_FUND_FLOW_JOB" (
  "JOB_ID" UUID PRIMARY KEY,
  "STAGE_CD" VARCHAR(30) NOT NULL,
  "FROM_DT" DATE NOT NULL,
  "TO_DT" DATE NOT NULL,
  "STS" VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
  "TOTAL_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "SUCCESS_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "EMPTY_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "FAILED_ITEM_CNT" INTEGER NOT NULL DEFAULT 0,
  "ERROR_MSG" VARCHAR(4000),
  "CRT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "START_DTTM" TIMESTAMP,
  "COMPLETE_DTTM" TIMESTAMP,
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_JOB_01" CHECK
    ("STAGE_CD" IN ('AGGREGATE','OFFERING','FUND_TYPE','FUND_KIND','VALID_VARIANT','ALL_ACTIVE')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_JOB_02" CHECK
    ("STS" IN ('QUEUED','RUNNING','COMPLETED','COMPLETED_WITH_ERRORS','FAILED')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_JOB_03" CHECK ("FROM_DT" <= "TO_DT")
);

CREATE UNIQUE INDEX "UX_KOFIA_CO_FUND_FLOW_JOB_ACTIVE"
  ON "TB_KOFIA_CO_FUND_FLOW_JOB"("STAGE_CD", "FROM_DT", "TO_DT")
  WHERE "STS" IN ('QUEUED','RUNNING');

CREATE TABLE "TB_KOFIA_CO_FUND_FLOW_JOB_ITEM" (
  "ITEM_ID" BIGSERIAL PRIMARY KEY,
  "JOB_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CO_FUND_FLOW_JOB"("JOB_ID") ON DELETE CASCADE,
  "VARIANT_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CO_FUND_FLOW_VARIANT"("VARIANT_ID"),
  "BASE_DT" DATE NOT NULL,
  "REQ_PARAMS" JSONB NOT NULL,
  "STS" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  "RECEIVED_CNT" INTEGER NOT NULL DEFAULT 0,
  "STORED_CNT" INTEGER NOT NULL DEFAULT 0,
  "RETRY_CNT" INTEGER NOT NULL DEFAULT 0,
  "ERROR_MSG" VARCHAR(4000),
  "START_DTTM" TIMESTAMP,
  "COMPLETE_DTTM" TIMESTAMP,
  CONSTRAINT "UX_KOFIA_CO_FUND_FLOW_JOB_ITEM_01" UNIQUE
    ("JOB_ID", "VARIANT_ID", "BASE_DT"),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_JOB_ITEM_01" CHECK
    ("STS" IN ('PENDING','RUNNING','SUCCESS','SUCCESS_EMPTY','FAILED'))
);

CREATE INDEX "IX_KOFIA_CO_FUND_FLOW_JOB_ITEM_01"
  ON "TB_KOFIA_CO_FUND_FLOW_JOB_ITEM"("JOB_ID", "STS", "BASE_DT", "ITEM_ID");

CREATE TABLE "TB_KOFIA_CO_FUND_FLOW_RAW_RSP" (
  "RAW_RSP_ID" UUID PRIMARY KEY,
  "JOB_ID" UUID REFERENCES "TB_KOFIA_CO_FUND_FLOW_JOB"("JOB_ID") ON DELETE SET NULL,
  "ITEM_ID" BIGINT REFERENCES "TB_KOFIA_CO_FUND_FLOW_JOB_ITEM"("ITEM_ID") ON DELETE SET NULL,
  "VARIANT_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CO_FUND_FLOW_VARIANT"("VARIANT_ID"),
  "BASE_DT" DATE NOT NULL,
  "REQ_PARAMS" JSONB NOT NULL,
  "ROW_CNT" INTEGER NOT NULL,
  "RAW_HASH" CHAR(64) NOT NULL,
  "PAYLOAD" JSONB NOT NULL,
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "IX_KOFIA_CO_FUND_FLOW_RAW_RSP_01"
  ON "TB_KOFIA_CO_FUND_FLOW_RAW_RSP"("VARIANT_ID", "BASE_DT");

CREATE TABLE "TB_KOFIA_CO_FUND_FLOW_ROW" (
  "VARIANT_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CO_FUND_FLOW_VARIANT"("VARIANT_ID"),
  "BASE_DT" DATE NOT NULL,
  "ROW_KEY" VARCHAR(700) NOT NULL,
  "COMPANY_TYP_CD" VARCHAR(20),
  "COMPANY_NM" VARCHAR(500),
  "FUND_TYP_CD" VARCHAR(10) NOT NULL,
  "FUND_KIND_CD" VARCHAR(10) NOT NULL,
  "OFFERING_TYP_CD" VARCHAR(10) NOT NULL,
  "ETF_INCLUDE_YN" CHAR(1) NOT NULL,
  "METRIC_01_VAL" NUMERIC(30,4),
  "METRIC_02_VAL" NUMERIC(30,4),
  "METRIC_03_VAL" NUMERIC(30,4),
  "METRIC_04_VAL" NUMERIC(30,4),
  "METRIC_05_VAL" NUMERIC(30,4),
  "METRIC_06_VAL" NUMERIC(30,4),
  "METRIC_07_VAL" NUMERIC(30,4),
  "METRIC_08_VAL" NUMERIC(30,4),
  "METRIC_09_VAL" NUMERIC(30,4),
  "PERIOD_CD" VARCHAR(10),
  "RAW_RSP_ID" UUID NOT NULL REFERENCES "TB_KOFIA_CO_FUND_FLOW_RAW_RSP"("RAW_RSP_ID"),
  "PAYLOAD" JSONB NOT NULL,
  "RAW_HASH" CHAR(64) NOT NULL,
  "FIRST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("VARIANT_ID", "BASE_DT", "ROW_KEY"),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_ROW_01" CHECK ("OFFERING_TYP_CD" IN ('*','1','2')),
  CONSTRAINT "CK_KOFIA_CO_FUND_FLOW_ROW_02" CHECK ("ETF_INCLUDE_YN" IN ('Y','N'))
);

CREATE INDEX "IX_KOFIA_CO_FUND_FLOW_ROW_01"
  ON "TB_KOFIA_CO_FUND_FLOW_ROW"("BASE_DT", "FUND_TYP_CD", "FUND_KIND_CD");

CREATE INDEX "IX_KOFIA_CO_FUND_FLOW_ROW_02"
  ON "TB_KOFIA_CO_FUND_FLOW_ROW"("COMPANY_TYP_CD", "COMPANY_NM", "BASE_DT");

COMMENT ON TABLE "TB_KOFIA_CO_FUND_FLOW_VARIANT" IS '회사별자금유출입 단계별 수집 파라미터 조합';
COMMENT ON TABLE "TB_KOFIA_CO_FUND_FLOW_JOB" IS '회사별자금유출입 영업일 스냅샷 수집 Job';
COMMENT ON TABLE "TB_KOFIA_CO_FUND_FLOW_JOB_ITEM" IS '회사별자금유출입 조합 및 기준일 실행 항목';
COMMENT ON TABLE "TB_KOFIA_CO_FUND_FLOW_RAW_RSP" IS '회사별자금유출입 파라미터 조합별 원본 응답';
COMMENT ON TABLE "TB_KOFIA_CO_FUND_FLOW_ROW" IS '회사별자금유출입 조합별 영업일 원천행';
COMMENT ON COLUMN "TB_KOFIA_CO_FUND_FLOW_ROW"."METRIC_01_VAL" IS 'FreeSIS TMPV2 원천값';
COMMENT ON COLUMN "TB_KOFIA_CO_FUND_FLOW_ROW"."METRIC_09_VAL" IS 'FreeSIS TMPV10 원천값';
