CREATE TABLE "TB_KOFIA_BND_OTC_INV_TRD" (
  "DATA_PRD_CD" VARCHAR(10) NOT NULL,
  "FROM_DT" DATE NOT NULL,
  "TO_DT" DATE NOT NULL,
  "VALUE_TYP_CD" VARCHAR(10) NOT NULL,
  "TRADE_TYP_NM" VARCHAR(100) NOT NULL,
  "BOND_TYP_NM" VARCHAR(100) NOT NULL,
  "INVESTOR_TYP_CD" VARCHAR(40) NOT NULL,
  "INVESTOR_TYP_NM" VARCHAR(100) NOT NULL,
  "REMAIN_FROM_MON" INTEGER NOT NULL DEFAULT 0,
  "REMAIN_TO_MON" INTEGER NOT NULL DEFAULT 0,
  "UNIT_MULTIPLIER" NUMERIC(20,0) NOT NULL,
  "TRD_VALUE" NUMERIC(30,4),
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" CHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (
    "DATA_PRD_CD", "FROM_DT", "TO_DT", "VALUE_TYP_CD", "TRADE_TYP_NM", "BOND_TYP_NM",
    "INVESTOR_TYP_CD", "REMAIN_FROM_MON", "REMAIN_TO_MON"
  ),
  CONSTRAINT "CK_KOFIA_BND_OTC_INV_TRD_01" CHECK ("FROM_DT" <= "TO_DT"),
  CONSTRAINT "CK_KOFIA_BND_OTC_INV_TRD_02" CHECK ("REMAIN_FROM_MON" >= 0),
  CONSTRAINT "CK_KOFIA_BND_OTC_INV_TRD_03" CHECK ("REMAIN_TO_MON" >= 0),
  CONSTRAINT "CK_KOFIA_BND_OTC_INV_TRD_04"
    CHECK ("DATA_STS" IN ('FRESH','STALE','MISSING','PARTIAL','ERROR'))
);

CREATE INDEX "IX_KOFIA_BND_OTC_INV_TRD_01"
  ON "TB_KOFIA_BND_OTC_INV_TRD"("TO_DT", "TRADE_TYP_NM", "BOND_TYP_NM");

CREATE INDEX "IX_KOFIA_BND_OTC_INV_TRD_02"
  ON "TB_KOFIA_BND_OTC_INV_TRD"("INVESTOR_TYP_CD", "TO_DT");

COMMENT ON TABLE "TB_KOFIA_BND_OTC_INV_TRD" IS '금융투자협회 채권 장외 투자자별 기간 집계 거래 현황';
COMMENT ON COLUMN "TB_KOFIA_BND_OTC_INV_TRD"."UNIT_MULTIPLIER" IS 'FreeSIS tmpV40 금액 표시 단위 배수';
COMMENT ON COLUMN "TB_KOFIA_BND_OTC_INV_TRD"."TRD_VALUE" IS 'FreeSIS 표시 단위 기준 거래대금 또는 거래량 값';
