CREATE TABLE "TB_KOFIA_FINAL_QUOTE_YLD" (
  "BASE_DT" DATE NOT NULL,
  "INSTRUMENT_NM" VARCHAR(200) NOT NULL,
  "REMAIN_TERM_NM" VARCHAR(100) NOT NULL,
  "MORNING_YLD_RT" NUMERIC(12,6),
  "AFTERNOON_YLD_RT" NUMERIC(12,6),
  "DAY_CHG_PT" NUMERIC(12,6),
  "PREV_YLD_RT" NUMERIC(12,6),
  "YEAR_HIGH_YLD_RT" NUMERIC(12,6),
  "YEAR_LOW_YLD_RT" NUMERIC(12,6),
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" CHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("BASE_DT", "INSTRUMENT_NM", "REMAIN_TERM_NM"),
  CONSTRAINT "CK_KOFIA_FINAL_QUOTE_YLD_01"
    CHECK ("DATA_STS" IN ('FRESH','STALE','MISSING','PARTIAL','ERROR'))
);

CREATE INDEX "IX_KOFIA_FINAL_QUOTE_YLD_01"
  ON "TB_KOFIA_FINAL_QUOTE_YLD"("INSTRUMENT_NM", "BASE_DT");

CREATE TABLE "TB_KOFIA_EQUITY_MKT_DAY" (
  "MKT_CD" VARCHAR(10) NOT NULL,
  "BASE_DT" DATE NOT NULL,
  "INDEX_VAL" NUMERIC(20,6),
  "TRD_QTY" NUMERIC(30,4),
  "TRD_AMT" NUMERIC(30,4),
  "MKT_CAP" NUMERIC(30,4),
  "FOREIGN_MKT_CAP" NUMERIC(30,4),
  "FOREIGN_MKT_CAP_RT" NUMERIC(12,6),
  "QTY_UNIT_MULTIPLIER" NUMERIC(20,0) NOT NULL,
  "AMT_UNIT_MULTIPLIER" NUMERIC(20,0) NOT NULL,
  "DATA_SRC_CD" VARCHAR(20) NOT NULL DEFAULT 'KOFIA',
  "RAW_HASH" CHAR(64) NOT NULL,
  "DATA_STS" VARCHAR(20) NOT NULL DEFAULT 'FRESH',
  "COLLECT_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPD_DTTM" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("MKT_CD", "BASE_DT"),
  CONSTRAINT "CK_KOFIA_EQUITY_MKT_DAY_01" CHECK ("MKT_CD" IN ('KOSPI','KOSDAQ')),
  CONSTRAINT "CK_KOFIA_EQUITY_MKT_DAY_02"
    CHECK ("DATA_STS" IN ('FRESH','STALE','MISSING','PARTIAL','ERROR'))
);

CREATE INDEX "IX_KOFIA_EQUITY_MKT_DAY_01"
  ON "TB_KOFIA_EQUITY_MKT_DAY"("BASE_DT", "MKT_CD");

COMMENT ON TABLE "TB_KOFIA_FINAL_QUOTE_YLD" IS '금융투자협회 최종호가수익률 기준일 스냅샷';
COMMENT ON COLUMN "TB_KOFIA_FINAL_QUOTE_YLD"."DAY_CHG_PT" IS '전일 대비 수익률 변화 퍼센트포인트';
COMMENT ON TABLE "TB_KOFIA_EQUITY_MKT_DAY" IS '금융투자협회 KOSPI 및 KOSDAQ 일별 시장 통계';
COMMENT ON COLUMN "TB_KOFIA_EQUITY_MKT_DAY"."TRD_QTY" IS 'QTY_UNIT_MULTIPLIER 기준 표시 거래량';
COMMENT ON COLUMN "TB_KOFIA_EQUITY_MKT_DAY"."TRD_AMT" IS 'AMT_UNIT_MULTIPLIER 기준 표시 거래대금';
