CREATE TABLE "TB_VOL_CONSOL_RUN" (
    "RUN_ID" UUID PRIMARY KEY,
    "TRIGGER_CD" VARCHAR(30) NOT NULL,
    "COLLECT_BASE_DT" DATE,
    "BASE_DT" DATE,
    "RULE_VER" VARCHAR(50) NOT NULL,
    "STS" VARCHAR(20) NOT NULL CHECK ("STS" IN ('RUNNING', 'CALCULATED', 'PARTIAL', 'FAILED', 'SKIPPED')),
    "MATCH_CNT" INTEGER,
    "START_DTTM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "END_DTTM" TIMESTAMPTZ,
    "RESULT_JSON" JSONB,
    "FAIL_RSN" TEXT
);
CREATE INDEX "IX_VOL_CONSOL_RUN_START" ON "TB_VOL_CONSOL_RUN" ("START_DTTM" DESC);
COMMENT ON TABLE "TB_VOL_CONSOL_RUN" IS 'KRX 수집 후 거래량 증가·횡보 후보 검색 실행 이력 및 결과 스냅샷';
COMMENT ON COLUMN "TB_VOL_CONSOL_RUN"."COLLECT_BASE_DT" IS '수집 완료 기준일 또는 수동 검색 요청 기준일';
COMMENT ON COLUMN "TB_VOL_CONSOL_RUN"."STS" IS 'CALCULATED도 수치 계산 완료만 의미하며 투자 검증 완료가 아님';
COMMENT ON COLUMN "TB_VOL_CONSOL_RUN"."RESULT_JSON" IS '계산 규칙, 범위, 잠정 후보, 제외 사유, 미확인 정보가 포함된 실행 당시 결과';
