CREATE TABLE TB_BRF_ITEM
(
    ITEM_CD     VARCHAR(30)  NOT NULL,
    ITEM_NM     VARCHAR(100) NOT NULL,
    SORT_NO     INTEGER      NOT NULL,
    ITEM_TP     VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y',
    ITEM_DESC   VARCHAR(500),
    CONSTRAINT PK_BRF_ITEM PRIMARY KEY (ITEM_CD),
    CONSTRAINT UK_BRF_ITEM_01 UNIQUE (SORT_NO),
    CONSTRAINT CK_BRF_ITEM_01 CHECK (SORT_NO BETWEEN 1 AND 15),
    CONSTRAINT CK_BRF_ITEM_02 CHECK (ITEM_TP IN ('NORMAL', 'FINAL')),
    CONSTRAINT CK_BRF_ITEM_03 CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE TB_BRF_ITEM IS '투자 브리핑의 14개 기본 항목과 종합판단 항목을 정의하는 기준 테이블';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_CD IS '브리핑 항목 코드. 예: US_MARKET, KR_MARKET, FINAL';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_NM IS '화면에 표시할 브리핑 항목 명칭';
COMMENT ON COLUMN TB_BRF_ITEM.SORT_NO IS '브리핑 항목 표시 순서. 1부터 15까지 사용';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_TP IS '브리핑 항목 유형. NORMAL은 일반 항목, FINAL은 종합판단';
COMMENT ON COLUMN TB_BRF_ITEM.USE_YN IS '브리핑 항목 사용 여부. Y는 사용, N은 미사용';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_DESC IS '브리핑 항목의 작성 목적과 포함 내용 설명';

CREATE TABLE TB_INV_BRF
(
    BRF_ID      BIGSERIAL    NOT NULL,
    BRF_DT      DATE         NOT NULL,
    BRF_TTL     VARCHAR(200) NOT NULL,
    BRF_ST      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    REG_DT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_DT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_INV_BRF PRIMARY KEY (BRF_ID),
    CONSTRAINT UK_INV_BRF_01 UNIQUE (BRF_DT),
    CONSTRAINT CK_INV_BRF_01 CHECK (BRF_ST IN ('DRAFT', 'COMPLETE', 'PUBLISHED'))
);

COMMENT ON TABLE TB_INV_BRF IS '날짜별 일일 투자 브리핑의 기본 정보를 저장하는 테이블';
COMMENT ON COLUMN TB_INV_BRF.BRF_ID IS '투자 브리핑 내부 식별번호';
COMMENT ON COLUMN TB_INV_BRF.BRF_DT IS '투자 브리핑 기준일자. 하루에 한 건만 등록';
COMMENT ON COLUMN TB_INV_BRF.BRF_TTL IS '투자 브리핑 제목';
COMMENT ON COLUMN TB_INV_BRF.BRF_ST IS '브리핑 상태. DRAFT는 작성 중, COMPLETE는 작성 완료, PUBLISHED는 게시 완료';
COMMENT ON COLUMN TB_INV_BRF.REG_DT IS '데이터 최초 등록 일시';
COMMENT ON COLUMN TB_INV_BRF.MOD_DT IS '데이터 최종 수정 일시';

INSERT INTO TB_INV_BRF (BRF_ID, BRF_DT, BRF_TTL, BRF_ST, REG_DT, MOD_DT)
SELECT briefing_id, briefing_date, title, briefing_status, created_at, updated_at
FROM tb_investment_briefing;

SELECT setval(
    pg_get_serial_sequence('tb_inv_brf', 'brf_id'),
    COALESCE((SELECT MAX(brf_id) FROM tb_inv_brf), 1),
    EXISTS (SELECT 1 FROM tb_inv_brf)
);

CREATE TABLE TB_BRF_DTL
(
    DTL_ID      BIGSERIAL    NOT NULL,
    BRF_ID      BIGINT       NOT NULL,
    ITEM_CD     VARCHAR(30)  NOT NULL,
    ITEM_SUM    VARCHAR(1000),
    ITEM_CONT   TEXT         NOT NULL,
    SIGNAL_CD   VARCHAR(20),
    ACT_YN      CHAR(1)      NOT NULL DEFAULT 'N',
    REG_DT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_DT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BRF_DTL PRIMARY KEY (DTL_ID),
    CONSTRAINT FK_BRF_DTL_01 FOREIGN KEY (BRF_ID)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BRF_DTL_02 FOREIGN KEY (ITEM_CD)
        REFERENCES TB_BRF_ITEM (ITEM_CD),
    CONSTRAINT UK_BRF_DTL_01 UNIQUE (BRF_ID, ITEM_CD),
    CONSTRAINT CK_BRF_DTL_01 CHECK (ACT_YN IN ('Y', 'N'))
);

COMMENT ON TABLE TB_BRF_DTL IS '날짜별 투자 브리핑의 14개 분석 항목과 종합판단 내용을 저장하는 상세 테이블';
COMMENT ON COLUMN TB_BRF_DTL.DTL_ID IS '투자 브리핑 상세 데이터 내부 식별번호';
COMMENT ON COLUMN TB_BRF_DTL.BRF_ID IS '일일 투자 브리핑 기본정보 식별번호';
COMMENT ON COLUMN TB_BRF_DTL.ITEM_CD IS '브리핑 항목 코드. TB_BRF_ITEM의 항목 코드를 참조';
COMMENT ON COLUMN TB_BRF_DTL.ITEM_SUM IS '브리핑 항목의 핵심 내용을 요약한 짧은 설명';
COMMENT ON COLUMN TB_BRF_DTL.ITEM_CONT IS '브리핑 항목의 전체 상세 내용';
COMMENT ON COLUMN TB_BRF_DTL.SIGNAL_CD IS '항목별 투자 또는 위험 신호 코드. 예: NORMAL, WATCH, CAUTION, RISK';
COMMENT ON COLUMN TB_BRF_DTL.ACT_YN IS '사용자의 매수·매도·중지 등 행동 필요 여부';
COMMENT ON COLUMN TB_BRF_DTL.REG_DT IS '상세 데이터 최초 등록 일시';
COMMENT ON COLUMN TB_BRF_DTL.MOD_DT IS '상세 데이터 최종 수정 일시';

CREATE TABLE TB_BRF_STK
(
    STK_SIG_ID  BIGSERIAL    NOT NULL,
    BRF_ID      BIGINT       NOT NULL,
    ACCT_TP     VARCHAR(20)  NOT NULL,
    STK_CD      VARCHAR(30)  NOT NULL,
    STK_NM      VARCHAR(100) NOT NULL,
    LIGHT_CD    VARCHAR(20),
    ACT_CD      VARCHAR(30),
    BUY_ST      VARCHAR(20),
    REBUY_CD    VARCHAR(20),
    RCM_AMT     NUMERIC(18, 2),
    RCM_RT      NUMERIC(10, 4),
    SIG_RSN     TEXT,
    MEMO        TEXT,
    REG_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BRF_STK PRIMARY KEY (STK_SIG_ID),
    CONSTRAINT FK_BRF_STK_01 FOREIGN KEY (BRF_ID)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE,
    CONSTRAINT UK_BRF_STK_01 UNIQUE (BRF_ID, ACCT_TP, STK_CD)
);

COMMENT ON TABLE TB_BRF_STK IS '일일 투자 브리핑에서 계좌 및 보유종목별 투자 신호를 저장하는 테이블';
COMMENT ON COLUMN TB_BRF_STK.STK_SIG_ID IS '종목별 브리핑 신호 내부 식별번호';
COMMENT ON COLUMN TB_BRF_STK.BRF_ID IS '종목 신호가 속한 일일 투자 브리핑 식별번호';
COMMENT ON COLUMN TB_BRF_STK.ACCT_TP IS '계좌 유형. GENERAL은 종합, ISA는 ISA, PENSION은 연금, DOMESTIC은 국내주식';
COMMENT ON COLUMN TB_BRF_STK.STK_CD IS '국내 종목코드 또는 해외주식 티커';
COMMENT ON COLUMN TB_BRF_STK.STK_NM IS '종목 또는 ETF 명칭';
COMMENT ON COLUMN TB_BRF_STK.LIGHT_CD IS '종목별 신호등 코드. GREEN, BLUE, YELLOW, RED 등을 사용';
COMMENT ON COLUMN TB_BRF_STK.ACT_CD IS '최종 행동신호. REGULAR_BUY, HOLD, PAUSE, REDUCE, SELL 등을 사용';
COMMENT ON COLUMN TB_BRF_STK.BUY_ST IS '해당 종목의 정기 모으기 상태. ACTIVE, PAUSED, STOPPED 등을 사용';
COMMENT ON COLUMN TB_BRF_STK.REBUY_CD IS '재매수 신호. WAIT, WATCH, PARTIAL, ALLOWED 등을 사용';
COMMENT ON COLUMN TB_BRF_STK.RCM_AMT IS '브리핑에서 제안한 종목별 추천 매수 금액';
COMMENT ON COLUMN TB_BRF_STK.RCM_RT IS '브리핑에서 제안한 추천 매도 또는 비중조절 비율';
COMMENT ON COLUMN TB_BRF_STK.SIG_RSN IS '해당 종목에 행동신호를 부여한 이유';
COMMENT ON COLUMN TB_BRF_STK.MEMO IS '종목별 추가 참고사항과 사용자 메모';
COMMENT ON COLUMN TB_BRF_STK.REG_DT IS '종목 신호 데이터 최초 등록 일시';
COMMENT ON COLUMN TB_BRF_STK.MOD_DT IS '종목 신호 데이터 최종 수정 일시';

ALTER TABLE tb_briefing_market_indicator
    DROP CONSTRAINT fk_market_briefing,
    ADD CONSTRAINT fk_market_briefing FOREIGN KEY (briefing_id)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE;
ALTER TABLE tb_briefing_account_strategy
    DROP CONSTRAINT fk_account_strategy_briefing,
    ADD CONSTRAINT fk_account_strategy_briefing FOREIGN KEY (briefing_id)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE;
ALTER TABLE tb_investment_execution
    DROP CONSTRAINT fk_execution_briefing,
    ADD CONSTRAINT fk_execution_briefing FOREIGN KEY (briefing_id)
        REFERENCES TB_INV_BRF (BRF_ID);
ALTER TABLE tb_briefing_evidence
    DROP CONSTRAINT fk_evidence_briefing,
    ADD CONSTRAINT fk_evidence_briefing FOREIGN KEY (briefing_id)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE;

DROP TABLE IF EXISTS tb_briefing_stock_signal;
DROP TABLE IF EXISTS tb_investment_briefing_item;
DROP TABLE IF EXISTS tb_briefing_item_definition;
DROP TABLE IF EXISTS tb_investment_briefing;
