ALTER TABLE TB_ANALYSIS
    ADD COLUMN TARGET_WEIGHT NUMERIC(10,6) NOT NULL DEFAULT 0,
    ADD COLUMN MARKET_RETURN_RT NUMERIC(10,4) NOT NULL DEFAULT 0,
    ADD COLUMN RISK_SCORE INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN CALC_REASON TEXT,
    ADD CONSTRAINT CK_ANALYSIS_07 CHECK (
        TARGET_WEIGHT >= 0 AND TARGET_WEIGHT <= 1
    ),
    ADD CONSTRAINT CK_ANALYSIS_08 CHECK (RISK_SCORE >= 0);

COMMENT ON COLUMN TB_ANALYSIS.ANALYSIS_DT IS '기준일';
COMMENT ON COLUMN TB_ANALYSIS.ACCT_TP IS '계좌';
COMMENT ON COLUMN TB_ANALYSIS.STK_CD IS '종목코드';
COMMENT ON COLUMN TB_ANALYSIS.CURRENT_WEIGHT IS '현재비중. 0부터 1 사이의 비율';
COMMENT ON COLUMN TB_ANALYSIS.TARGET_WEIGHT IS '목표비중. 0부터 1 사이의 비율';
COMMENT ON COLUMN TB_ANALYSIS.WEIGHT_ST IS '비중상태: UNDER, NORMAL, OVER';
COMMENT ON COLUMN TB_ANALYSIS.MARKET_RETURN_RT IS '시장하락률 또는 시장수익률. 백분율 값';
COMMENT ON COLUMN TB_ANALYSIS.MARKET_PHASE IS '시장국면: NORMAL, CORRECTION, STRONG_CORRECTION, CRASH';
COMMENT ON COLUMN TB_ANALYSIS.RISK_SCORE IS '위험 계산점수';
COMMENT ON COLUMN TB_ANALYSIS.RISK_LEVEL IS '위험등급: LOW, MEDIUM, HIGH, VERY_HIGH';
COMMENT ON COLUMN TB_ANALYSIS.REGULAR_BUY_SIG IS '정기매수신호';
COMMENT ON COLUMN TB_ANALYSIS.ADD_BUY_AMT IS '추가매수금액';
COMMENT ON COLUMN TB_ANALYSIS.REBUY_SIG IS '재매수신호';
COMMENT ON COLUMN TB_ANALYSIS.FINAL_ACTION IS '최종행동신호';
COMMENT ON COLUMN TB_ANALYSIS.CALC_REASON IS '분석 결과와 최종 행동신호의 계산사유';
