ALTER TABLE TB_ANALYSIS
    DROP CONSTRAINT CK_ANALYSIS_07,
    ADD COLUMN PURCHASE_AMT NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN PROFIT_AMT NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN STOCK_RETURN_RT NUMERIC(10,4) NOT NULL DEFAULT 0,
    ADD COLUMN WEIGHT_DIFF NUMERIC(10,4) NOT NULL DEFAULT 0,
    ADD CONSTRAINT CK_ANALYSIS_07 CHECK (
        TARGET_WEIGHT >= 0 AND TARGET_WEIGHT <= 100
    ),
    ADD CONSTRAINT CK_ANALYSIS_09 CHECK (
        CURRENT_WEIGHT >= 0 AND CURRENT_WEIGHT <= 100
    );

COMMENT ON COLUMN TB_ANALYSIS.PURCHASE_AMT IS '매입금액. 보유수량과 평균매입단가의 곱';
COMMENT ON COLUMN TB_ANALYSIS.MARKET_VALUE IS '평가금액. 보유수량과 현재가의 곱';
COMMENT ON COLUMN TB_ANALYSIS.PROFIT_AMT IS '손익금액. 평가금액에서 매입금액을 차감한 값';
COMMENT ON COLUMN TB_ANALYSIS.STOCK_RETURN_RT IS '종목수익률. (현재가-평단가)/평단가*100';
COMMENT ON COLUMN TB_ANALYSIS.CURRENT_WEIGHT IS '현재비중. 평가금액/계좌 총평가금액*100';
COMMENT ON COLUMN TB_ANALYSIS.TARGET_WEIGHT IS '목표비중. 백분율 값 0부터 100';
COMMENT ON COLUMN TB_ANALYSIS.WEIGHT_DIFF IS '비중차이. 현재비중에서 목표비중을 차감한 값';
