ALTER TABLE TB_ANALYSIS
    ADD COLUMN MAX_WEIGHT NUMERIC(10,4) NOT NULL DEFAULT 0,
    ADD CONSTRAINT CK_ANALYSIS_10 CHECK (MAX_WEIGHT >= 0);

COMMENT ON COLUMN TB_ANALYSIS.MAX_WEIGHT IS
'허용 최대비중. 목표비중 × (1 + 초과 허용률)로 계산한 백분율 값';
