CREATE TABLE TB_MKT_CAL (
    CAL_DT       DATE NOT NULL,
    MARKET_CD    VARCHAR(20) NOT NULL,
    OPEN_YN      CHAR(1) NOT NULL DEFAULT 'Y',
    HOLIDAY_NM   VARCHAR(100),
    REG_DT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_DT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MKT_CAL PRIMARY KEY (CAL_DT, MARKET_CD),
    CONSTRAINT CK_MKT_CAL_01 CHECK (MARKET_CD IN ('KRX', 'US')),
    CONSTRAINT CK_MKT_CAL_02 CHECK (OPEN_YN IN ('Y', 'N'))
);

COMMENT ON TABLE TB_MKT_CAL IS '국내 및 미국 주식시장의 영업일과 휴장일을 관리하는 테이블';
COMMENT ON COLUMN TB_MKT_CAL.CAL_DT IS '시장 달력 기준일';
COMMENT ON COLUMN TB_MKT_CAL.MARKET_CD IS '시장 코드: KRX 또는 US';
COMMENT ON COLUMN TB_MKT_CAL.OPEN_YN IS '시장 개장 여부';
COMMENT ON COLUMN TB_MKT_CAL.HOLIDAY_NM IS '휴장일 또는 공휴일 명칭';
COMMENT ON COLUMN TB_MKT_CAL.REG_DT IS '최초 등록 일시';
COMMENT ON COLUMN TB_MKT_CAL.MOD_DT IS '최종 수정 일시';
