ALTER TABLE TB_BRF_ITEM
    ADD COLUMN BRF_ITEM_ID BIGSERIAL,
    ADD COLUMN BRF_ID      BIGINT,
    ADD COLUMN ITEM_SUM    VARCHAR(1000),
    ADD COLUMN ITEM_CONT   TEXT,
    ADD COLUMN SIGNAL_CD   VARCHAR(20),
    ADD COLUMN ACT_YN      CHAR(1)   NOT NULL DEFAULT 'N',
    ADD COLUMN REG_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN MOD_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TB_BRF_ITEM
    ADD CONSTRAINT UK_BRF_ITEM_02 UNIQUE (BRF_ITEM_ID),
    ADD CONSTRAINT FK_BRF_ITEM_01 FOREIGN KEY (BRF_ID)
        REFERENCES TB_INV_BRF (BRF_ID) ON DELETE CASCADE,
    ADD CONSTRAINT CK_BRF_ITEM_04 CHECK (ACT_YN IN ('Y', 'N'));

COMMENT ON COLUMN TB_BRF_ITEM.BRF_ITEM_ID IS '브리핑 항목 내부 식별번호';
COMMENT ON COLUMN TB_BRF_ITEM.BRF_ID IS '투자 브리핑 식별번호';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_SUM IS '브리핑 항목의 핵심 내용 요약';
COMMENT ON COLUMN TB_BRF_ITEM.ITEM_CONT IS '브리핑 항목의 전체 상세 내용';
COMMENT ON COLUMN TB_BRF_ITEM.SIGNAL_CD IS '항목별 투자 또는 위험 신호 코드';
COMMENT ON COLUMN TB_BRF_ITEM.ACT_YN IS '사용자의 행동 필요 여부. Y는 필요, N은 불필요';
COMMENT ON COLUMN TB_BRF_ITEM.REG_DT IS '데이터 최초 등록 일시';
COMMENT ON COLUMN TB_BRF_ITEM.MOD_DT IS '데이터 최종 수정 일시';
