ALTER TABLE TB_BRIEFING_ACCOUNT_STRATEGY
    RENAME TO TB_BRF_ACCT_STRG;

ALTER TABLE TB_BRIEFING_EVIDENCE
    RENAME TO TB_BRF_EVDC;

ALTER TABLE TB_BRIEFING_MARKET_INDICATOR
    RENAME TO TB_BRF_MKT_IND;

ALTER TABLE TB_COMMON_CODE
    RENAME TO TB_COM_CD;
