COMMENT ON TABLE TB_KRX_INDEX_DAILY_PRICE IS 'KRX KOSPI 지수 일별 시세';

COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.id IS '내부 식별자';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.base_date IS '기준일자';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.index_class IS '계열구분';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.index_name IS '지수명';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.close_price IS '종가';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.change_amount IS '전일 대비';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.change_rate IS '등락률';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.open_price IS '시가';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.high_price IS '고가';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.low_price IS '저가';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.trading_volume IS '누적 거래량';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.trading_value IS '누적 거래대금';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.market_cap IS '상장 시가총액';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.created_at IS '최초 등록일시';
COMMENT ON COLUMN TB_KRX_INDEX_DAILY_PRICE.updated_at IS '최종 수정일시';
