ALTER TABLE TB_INVESTMENT_DECISION
    RENAME TO TB_INV_DEC;

ALTER TABLE TB_INVESTMENT_EXECUTION
    RENAME TO TB_INV_EXEC;

ALTER TABLE TB_INVESTMENT_STOCK_DECISION
    RENAME TO TB_INV_STK_DEC;

ALTER TABLE TB_KRX_COLLECTION_JOB
    RENAME TO TB_KRX_CLCT_JOB;

ALTER TABLE TB_KRX_COLLECTION_JOB_ITEM
    RENAME TO TB_KRX_CLCT_JOB_ITEM;

ALTER TABLE TB_KRX_DATASET_ROW
    RENAME TO TB_KRX_DATA_ROW;
