ALTER TABLE "TB_BUY_SET"
    ADD COLUMN "MKT_CD"          VARCHAR(10),
    ADD COLUMN "BASE_CYCLE_TP"   VARCHAR(20),
    ADD COLUMN "BASE_WEEK_DAY"   VARCHAR(20),
    ADD COLUMN "BASE_MONTH_DAY"  INTEGER,
    ADD COLUMN "BASE_AMT"        NUMERIC(18, 2),
    ADD COLUMN "BASE_QTY"        NUMERIC(18, 6),
    ADD COLUMN "BASE_PAUSE_RSN"  TEXT,
    ADD COLUMN "PRIORITY"        INTEGER,
    ADD COLUMN "EXEC_ST"         VARCHAR(20),
    ADD COLUMN "MONTH_EST_AMT"   NUMERIC(18, 2),
    ADD COLUMN "EXEC_NO"         INTEGER,
    ADD COLUMN "MEMO"            TEXT;

ALTER TABLE "TB_BUY_SET"
    ADD CONSTRAINT "UK_BUY_SET_01" UNIQUE ("ACCT_TP", "STK_CD"),
    ADD CONSTRAINT "CK_BUY_SET_01"
        CHECK ("BASE_MONTH_DAY" IS NULL OR "BASE_MONTH_DAY" BETWEEN 1 AND 31),
    ADD CONSTRAINT "CK_BUY_SET_02"
        CHECK ("PRIORITY" IS NULL OR "PRIORITY" > 0),
    ADD CONSTRAINT "CK_BUY_SET_03"
        CHECK ("EXEC_NO" IS NULL OR "EXEC_NO" > 0);

COMMENT ON COLUMN "TB_BUY_SET"."MKT_CD" IS '거래 시장 코드. KO는 국내, US는 미국';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_CYCLE_TP" IS '기본 모으기 주기 유형';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_WEEK_DAY" IS '기본 모으기 실행 요일';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_MONTH_DAY" IS '기본 모으기 실행 일자';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_AMT" IS '기본 회차별 모으기 금액';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_QTY" IS '기본 회차별 모으기 수량';
COMMENT ON COLUMN "TB_BUY_SET"."BASE_PAUSE_RSN" IS '기본 모으기 중단 이유';
COMMENT ON COLUMN "TB_BUY_SET"."PRIORITY" IS '모으기 우선순위';
COMMENT ON COLUMN "TB_BUY_SET"."EXEC_ST" IS '오늘 실행 상태';
COMMENT ON COLUMN "TB_BUY_SET"."MONTH_EST_AMT" IS '월 예상 투자 금액';
COMMENT ON COLUMN "TB_BUY_SET"."EXEC_NO" IS '당일 실행 순번';
COMMENT ON COLUMN "TB_BUY_SET"."MEMO" IS '모으기 관리 비고';
