CREATE TABLE "TB_STK" (
    "MKT_CD"      VARCHAR(10)  NOT NULL,
    "STK_CD"      VARCHAR(30)  NOT NULL,
    "STK_NM"      VARCHAR(100) NOT NULL,
    "LIST_SCOPE"  VARCHAR(20)  NOT NULL,
    "ASSET_TP"    VARCHAR(30),
    "EXCH_NM"     VARCHAR(50),
    "CURR"        VARCHAR(10),
    "PRVDR"       VARCHAR(30),
    "ACTV_YN"     CHAR(1)      NOT NULL DEFAULT 'Y',
    "REG_DT"      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MOD_DT"      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_STK" PRIMARY KEY ("MKT_CD", "STK_CD"),
    CONSTRAINT "CK_STK_01" CHECK ("MKT_CD" IN ('KO', 'US')),
    CONSTRAINT "CK_STK_02" CHECK ("LIST_SCOPE" IN ('DOMESTIC', 'OVERSEAS')),
    CONSTRAINT "CK_STK_03" CHECK ("ACTV_YN" IN ('Y', 'N'))
);

INSERT INTO "TB_STK"
    ("MKT_CD", "STK_CD", "STK_NM", "LIST_SCOPE", "ASSET_TP",
     "EXCH_NM", "CURR", "PRVDR", "ACTV_YN", "REG_DT", "MOD_DT")
SELECT
    CASE WHEN "LIST_SCOPE" = 'DOMESTIC' THEN 'KO' ELSE 'US' END,
    "STK_CD", MAX("STK_NM"), "LIST_SCOPE", MAX("ASSET_TP"),
    MAX("EXCH_NM"), MAX("CURR"), MAX("PRVDR"), MAX("ACTV_YN"),
    MIN("REG_DT"), MAX("MOD_DT")
FROM "TB_HOLD"
GROUP BY "LIST_SCOPE", "STK_CD";

CREATE TABLE "TB_ACCT_STK" (
    "ACCT_TP"  VARCHAR(20) NOT NULL,
    "MKT_CD"   VARCHAR(10) NOT NULL,
    "STK_CD"   VARCHAR(30) NOT NULL,
    "QTY"      NUMERIC(18, 6),
    "AVG_PRC"  NUMERIC(18, 4),
    "REG_DT"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MOD_DT"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_ACCT_STK" PRIMARY KEY ("ACCT_TP", "MKT_CD", "STK_CD"),
    CONSTRAINT "FK_ACCT_STK_01" FOREIGN KEY ("ACCT_TP")
        REFERENCES "TB_ACCT" ("ACCT_TP"),
    CONSTRAINT "FK_ACCT_STK_02" FOREIGN KEY ("MKT_CD", "STK_CD")
        REFERENCES "TB_STK" ("MKT_CD", "STK_CD") ON DELETE CASCADE
);

INSERT INTO "TB_ACCT_STK"
    ("ACCT_TP", "MKT_CD", "STK_CD", "QTY", "AVG_PRC", "REG_DT", "MOD_DT")
SELECT "MKT_SCOPE",
       CASE WHEN "LIST_SCOPE" = 'DOMESTIC' THEN 'KO' ELSE 'US' END,
       "STK_CD", "QTY", "AVG_PRC", "REG_DT", "MOD_DT"
FROM "TB_HOLD";

ALTER TABLE "TB_STK_SET" DROP CONSTRAINT "fk_stk_set_01";
ALTER TABLE "TB_STK_SET"
    ADD COLUMN "MKT_CD" VARCHAR(10);
UPDATE "TB_STK_SET" s
SET "MKT_CD" = a."MKT_CD"
FROM "TB_ACCT_STK" a
WHERE a."ACCT_TP" = s."ACCT_TP" AND a."STK_CD" = s."STK_CD";
ALTER TABLE "TB_STK_SET" ALTER COLUMN "MKT_CD" SET NOT NULL;
ALTER TABLE "TB_STK_SET"
    ADD CONSTRAINT "FK_STK_SET_01" FOREIGN KEY ("ACCT_TP", "MKT_CD", "STK_CD")
        REFERENCES "TB_ACCT_STK" ("ACCT_TP", "MKT_CD", "STK_CD") ON DELETE CASCADE;

ALTER TABLE "TB_ANALYSIS" DROP CONSTRAINT "fk_analysis_01";
ALTER TABLE "TB_ANALYSIS"
    ADD COLUMN "MKT_CD" VARCHAR(10);
UPDATE "TB_ANALYSIS" x
SET "MKT_CD" = a."MKT_CD"
FROM "TB_ACCT_STK" a
WHERE a."ACCT_TP" = x."ACCT_TP" AND a."STK_CD" = x."STK_CD";
ALTER TABLE "TB_ANALYSIS" ALTER COLUMN "MKT_CD" SET NOT NULL;
ALTER TABLE "TB_ANALYSIS"
    ADD CONSTRAINT "FK_ANALYSIS_01" FOREIGN KEY ("ACCT_TP", "MKT_CD", "STK_CD")
        REFERENCES "TB_ACCT_STK" ("ACCT_TP", "MKT_CD", "STK_CD") ON DELETE CASCADE;

ALTER TABLE "TB_STK_PRC"
    DROP CONSTRAINT "fk_overseas_daily_stock",
    DROP CONSTRAINT "ck_overseas_daily_market_scope",
    DROP CONSTRAINT "uk_overseas_daily_symbol_date";
DROP VIEW tb_stk_prc;
ALTER TABLE "TB_STK_PRC"
    ADD COLUMN "MKT_CD" VARCHAR(10);
UPDATE "TB_STK_PRC" SET "MKT_CD" = 'US';
ALTER TABLE "TB_STK_PRC" ALTER COLUMN "MKT_CD" SET NOT NULL;
ALTER TABLE "TB_STK_PRC" RENAME COLUMN "SYM" TO "STK_CD";
ALTER TABLE "TB_STK_PRC" DROP COLUMN "MKT_SCOPE";
ALTER TABLE "TB_STK_PRC"
    ADD CONSTRAINT "UK_STK_PRC_01" UNIQUE ("MKT_CD", "STK_CD", "TRD_DT"),
    ADD CONSTRAINT "FK_STK_PRC_01" FOREIGN KEY ("MKT_CD", "STK_CD")
        REFERENCES "TB_STK" ("MKT_CD", "STK_CD") ON DELETE CASCADE;

INSERT INTO "TB_STK_PRC"
    ("MKT_CD", "STK_CD", "TRD_DT", "OPEN_PRC", "HIGH_PRC", "LOW_PRC",
     "CLS_PRC", "ADJ_CLS", "VOL", "PRVDR")
SELECT DISTINCT ON (r."BASE_DT", r."PAYLOAD"->>'ISU_CD')
    'KO', r."PAYLOAD"->>'ISU_CD', r."BASE_DT",
    NULLIF(replace(r."PAYLOAD"->>'TDD_OPNPRC', ',', ''), '')::numeric,
    NULLIF(replace(r."PAYLOAD"->>'TDD_HGPRC', ',', ''), '')::numeric,
    NULLIF(replace(r."PAYLOAD"->>'TDD_LWPRC', ',', ''), '')::numeric,
    NULLIF(replace(r."PAYLOAD"->>'TDD_CLSPRC', ',', ''), '')::numeric,
    NULLIF(replace(r."PAYLOAD"->>'TDD_CLSPRC', ',', ''), '')::numeric,
    COALESCE(NULLIF(replace(r."PAYLOAD"->>'ACC_TRDVOL', ',', ''), '')::bigint, 0),
    'KRX'
FROM "TB_KRX_DATA_ROW" r
JOIN "TB_STK" s
  ON s."MKT_CD" = 'KO' AND s."STK_CD" = r."PAYLOAD"->>'ISU_CD'
WHERE r."DATA_CD" IN ('KOSPI_STOCK_DAILY', 'KOSDAQ_STOCK_DAILY', 'ETF_DAILY')
  AND r."BASE_DT" BETWEEN DATE '2026-07-01' AND DATE '2026-07-28'
  AND NULLIF(r."PAYLOAD"->>'TDD_CLSPRC', '') IS NOT NULL
ON CONFLICT ("MKT_CD", "STK_CD", "TRD_DT") DO NOTHING;

CREATE VIEW tb_stk_prc AS
SELECT "ID" AS id, "STK_CD" AS symbol, "TRD_DT" AS trading_day,
       "OPEN_PRC" AS open_price, "HIGH_PRC" AS high_price, "LOW_PRC" AS low_price,
       "CLS_PRC" AS close_price, "ADJ_CLS" AS adjusted_close, "VOL" AS volume,
       "PRVDR" AS provider, "REG_DT" AS created_at, "MOD_DT" AS updated_at,
       CASE WHEN "MKT_CD" = 'US' THEN 'GENERAL' ELSE 'DOMESTIC' END AS market_scope
FROM "TB_STK_PRC";

DROP VIEW vw_account_stock;
DROP VIEW tb_hold;
DROP TABLE "TB_HOLD";

CREATE VIEW tb_hold AS
SELECT a."ACCT_TP" AS market_scope, s."STK_CD" AS stock_code,
       s."STK_NM" AS stock_name, s."LIST_SCOPE" AS listing_scope,
       s."ASSET_TP" AS asset_type, s."EXCH_NM" AS exchange_name,
       s."CURR" AS currency, s."PRVDR" AS provider, s."ACTV_YN" AS active_yn,
       a."REG_DT" AS created_at, a."MOD_DT" AS updated_at,
       a."QTY" AS qty, a."AVG_PRC" AS avg_prc
FROM "TB_ACCT_STK" a
JOIN "TB_STK" s ON s."MKT_CD" = a."MKT_CD" AND s."STK_CD" = a."STK_CD";

COMMENT ON TABLE "TB_STK" IS '국내외 통합 종목 마스터';
COMMENT ON TABLE "TB_ACCT_STK" IS '국내·해외·ISA·연금 계좌별 보유종목';
COMMENT ON TABLE "TB_STK_PRC" IS '국내외 통합 종목 일별 OHLCV 시세';
