ALTER TABLE "TB_ACCT"
    ADD COLUMN "ADD_INV_CASH" NUMERIC(20, 2) NOT NULL DEFAULT 0,
    ADD COLUMN "MAX_INV_AMT" NUMERIC(20, 2) NOT NULL DEFAULT 0,
    ADD COLUMN "ACCT_DESC" VARCHAR(500);

ALTER TABLE "TB_ACCT" DROP CONSTRAINT "ck_acct_01";
ALTER TABLE "TB_ACCT"
    ADD CONSTRAINT "CK_ACCT_01"
        CHECK ("ACCT_TP" IN ('GENERAL', 'DOMESTIC', 'ISA', 'PENSION', 'MIRAE'));

COMMENT ON COLUMN "TB_ACCT"."AVAIL_CASH" IS '현재 투자 가능 현금';
COMMENT ON COLUMN "TB_ACCT"."ADD_INV_CASH" IS '추가 투자 가능 현금';
COMMENT ON COLUMN "TB_ACCT"."MAX_INV_AMT" IS '1회 최대 투입 한도';
COMMENT ON COLUMN "TB_ACCT"."ACCT_DESC" IS '계좌 투자 목적 및 운용 설명';
COMMENT ON COLUMN "TB_ACCT"."TOT_AMT" IS '총 가용 현금: 현재 투자 가능 현금과 추가 투자 가능 현금의 합계';

INSERT INTO "TB_ACCT"
    ("ACCT_TP", "ACCT_NM", "TOT_AMT", "AVAIL_CASH", "ADD_INV_CASH",
     "MAX_INV_AMT", "ACCT_DESC", "CURR", "USE_YN")
VALUES
    ('GENERAL', '종합계좌', 2209882, 709882, 1500000, 500000,
     '개별주, AI, 성장주, 산업재, 테마주', 'KRW', 'Y'),
    ('ISA', 'ISA', 11835422, 11335422, 500000, 1000000,
     'ETF 중심, 배당, 반도체, 금융, 산업재', 'KRW', 'Y'),
    ('PENSION', '연금계좌', 1584191, 1084191, 500000, 500000,
     'S&P500, 배당ETF, 채권, 단기채, MMF', 'KRW', 'Y'),
    ('MIRAE', '미래에셋증권', 100000, 0, 100000, 200000,
     '국내주식 금액 단위 신규 모으기 전용', 'KRW', 'Y')
ON CONFLICT ("ACCT_TP") DO UPDATE
SET "ACCT_NM" = EXCLUDED."ACCT_NM",
    "TOT_AMT" = EXCLUDED."TOT_AMT",
    "AVAIL_CASH" = EXCLUDED."AVAIL_CASH",
    "ADD_INV_CASH" = EXCLUDED."ADD_INV_CASH",
    "MAX_INV_AMT" = EXCLUDED."MAX_INV_AMT",
    "ACCT_DESC" = EXCLUDED."ACCT_DESC",
    "CURR" = EXCLUDED."CURR",
    "USE_YN" = EXCLUDED."USE_YN",
    "MOD_DT" = CURRENT_TIMESTAMP;

ALTER TABLE "TB_ACCT"
    ADD CONSTRAINT "CK_ACCT_CASH_01"
        CHECK ("AVAIL_CASH" >= 0 AND "ADD_INV_CASH" >= 0 AND "MAX_INV_AMT" >= 0),
    ADD CONSTRAINT "CK_ACCT_CASH_02"
        CHECK ("TOT_AMT" = "AVAIL_CASH" + "ADD_INV_CASH");

