ALTER TABLE "TB_STK_SET"
    ADD COLUMN "WGT_SCR" INTEGER;

ALTER TABLE "TB_STK_SET"
    ADD CONSTRAINT "CK_STK_SET_03"
        CHECK ("WGT_SCR" IS NULL OR "WGT_SCR" BETWEEN 1 AND 5);

COMMENT ON COLUMN "TB_STK_SET"."WGT_SCR" IS '자동 목표비중 산정에 사용하는 비중점수';

INSERT INTO "TB_STK_SET"
    ("ACCT_TP", "MKT_CD", "STK_CD", "STK_GRD", "BM_CD", "WGT_SCR", "TGT_WGT")
VALUES
    ('DOMESTIC', 'KO', '298040', 'CORE', '미국원자력·전력', 5, 0.1064)
ON CONFLICT ("ACCT_TP", "STK_CD") DO UPDATE
SET "STK_GRD" = EXCLUDED."STK_GRD",
    "BM_CD" = EXCLUDED."BM_CD",
    "WGT_SCR" = EXCLUDED."WGT_SCR",
    "TGT_WGT" = EXCLUDED."TGT_WGT",
    "MOD_DT" = CURRENT_TIMESTAMP;

