UPDATE "TB_ACCT_STK"
SET "QTY" = 4.000000,
    "AVG_PRC" = 40797,
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'DOMESTIC'
  AND "MKT_CD" = 'KO'
  AND "STK_CD" = '007340';

UPDATE "TB_STK_SET"
SET "STK_GRD" = 'SATELLITE',
    "TGT_WGT" = 0.064,
    "BM_CD" = '국내산업재',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'DOMESTIC'
  AND "MKT_CD" = 'KO'
  AND "STK_CD" = '007340';

INSERT INTO "TB_ANALYSIS"
    ("ANLYS_DT", "ACCT_TP", "MKT_CD", "STK_CD",
     "MKT_VAL", "CUR_WGT", "TGT_WGT", "WGT_DIFF", "MAX_WGT", "WGT_ST",
     "MKT_PHASE", "RISK_LVL", "RISK_SCORE", "MKT_RTN_RT",
     "REG_BUY_SIG", "ADD_BUY_AMT", "REBUY_SIG", "FINAL_ACT",
     "PUR_AMT", "PFT_AMT", "STK_RTN_RT", "CALC_RSN")
VALUES
    (DATE '2026-07-29', 'DOMESTIC', 'KO', '007340',
     146600, 1.3, 6.4, 5.1, 6.4, 'UNDER',
     'CORRECTION', 'MEDIUM', 51, 0,
     'NOT_SCHEDULED', 0, 'WATCH', 'ADDITIONAL_BUY',
     163188, -16588, -10.2,
     '현재가 36,650원. 비중부족, 조정, 중위험. 추가매수 검토.')
ON CONFLICT ("ANLYS_DT", "ACCT_TP", "STK_CD") DO UPDATE
SET "MKT_CD" = EXCLUDED."MKT_CD",
    "MKT_VAL" = EXCLUDED."MKT_VAL",
    "CUR_WGT" = EXCLUDED."CUR_WGT",
    "TGT_WGT" = EXCLUDED."TGT_WGT",
    "WGT_DIFF" = EXCLUDED."WGT_DIFF",
    "MAX_WGT" = EXCLUDED."MAX_WGT",
    "WGT_ST" = EXCLUDED."WGT_ST",
    "MKT_PHASE" = EXCLUDED."MKT_PHASE",
    "RISK_LVL" = EXCLUDED."RISK_LVL",
    "RISK_SCORE" = EXCLUDED."RISK_SCORE",
    "MKT_RTN_RT" = EXCLUDED."MKT_RTN_RT",
    "REG_BUY_SIG" = EXCLUDED."REG_BUY_SIG",
    "ADD_BUY_AMT" = EXCLUDED."ADD_BUY_AMT",
    "REBUY_SIG" = EXCLUDED."REBUY_SIG",
    "FINAL_ACT" = EXCLUDED."FINAL_ACT",
    "PUR_AMT" = EXCLUDED."PUR_AMT",
    "PFT_AMT" = EXCLUDED."PFT_AMT",
    "STK_RTN_RT" = EXCLUDED."STK_RTN_RT",
    "CALC_RSN" = EXCLUDED."CALC_RSN",
    "MOD_DT" = CURRENT_TIMESTAMP;
