ALTER TABLE "TB_ANALYSIS"
    DROP CONSTRAINT "ck_analysis_01";

ALTER TABLE "TB_ANALYSIS"
    ADD CONSTRAINT "CK_ANALYSIS_01"
        CHECK ("WGT_ST" IN ('UNDER', 'NORMAL', 'OVER', 'UNSET'));

COMMENT ON COLUMN "TB_ANALYSIS"."WGT_ST"
    IS '비중 상태: UNDER 비중부족, NORMAL 적정, OVER 비중초과, UNSET 목표비중 미설정';
