CREATE TABLE IF NOT EXISTS TB_KRX_COLLECTION_JOB (
 id UUID PRIMARY KEY,
 base_date DATE NOT NULL,
 status VARCHAR(30) NOT NULL,
 total_count INTEGER NOT NULL DEFAULT 0,
 success_count INTEGER NOT NULL DEFAULT 0,
 failed_count INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 started_at TIMESTAMP,
 completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_KRX_COLLECTION_JOB_ITEM (
 id BIGSERIAL PRIMARY KEY,
 job_id UUID NOT NULL REFERENCES TB_KRX_COLLECTION_JOB(id) ON DELETE CASCADE,
 dataset_code VARCHAR(50) NOT NULL,
 status VARCHAR(20) NOT NULL,
 received_count INTEGER NOT NULL DEFAULT 0,
 stored_count BIGINT NOT NULL DEFAULT 0,
 error_message VARCHAR(4000),
 started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMP,
 CONSTRAINT UK_KRX_COLLECTION_JOB_ITEM UNIQUE(job_id, dataset_code)
);

CREATE INDEX IF NOT EXISTS IX_KRX_COLLECTION_JOB_CREATED
 ON TB_KRX_COLLECTION_JOB(created_at DESC);

COMMENT ON TABLE TB_KRX_COLLECTION_JOB IS 'KRX 전체 수집 비동기 작업';
COMMENT ON TABLE TB_KRX_COLLECTION_JOB_ITEM IS 'KRX 수집 작업 데이터셋별 실행 결과';
