-- Yahoo Finance 주요 글로벌 지수 기준정보
INSERT INTO "TB_IDX"("IDX_CD","IDX_NM","IDX_NM_EN","IDX_TP","MKT_CD","CNTRY_CD","CURR_CD","DATA_SRC_CD","SRC_SYMBOL","DFLT_YN","CRT_USR_ID","UPD_USR_ID") VALUES
('SP500','S&P500','S&P 500 Index','MARKET','US','US','USD','YAHOO','^GSPC','Y','SYSTEM','SYSTEM'),
('NASDAQ_COMPOSITE','나스닥 종합','NASDAQ Composite','MARKET','NASDAQ','US','USD','YAHOO','^IXIC','Y','SYSTEM','SYSTEM'),
('DOW_JONES','다우지수','Dow Jones Industrial Average','MARKET','NYSE','US','USD','YAHOO','^DJI','N','SYSTEM','SYSTEM'),
('PHLX_SEMICONDUCTOR','필라델피아 반도체','PHLX Semiconductor Sector Index','SECTOR','NASDAQ','US','USD','YAHOO','^SOX','Y','SYSTEM','SYSTEM'),
('VIX','VIX','CBOE Volatility Index','MARKET','CBOE','US','USD','YAHOO','^VIX','Y','SYSTEM','SYSTEM'),
('NIKKEI225','닛케이225','Nikkei 225','MARKET','JP','JP','JPY','YAHOO','^N225','N','SYSTEM','SYSTEM')
ON CONFLICT("IDX_CD") DO UPDATE SET
 "IDX_NM"=EXCLUDED."IDX_NM","IDX_NM_EN"=EXCLUDED."IDX_NM_EN","IDX_TP"=EXCLUDED."IDX_TP",
 "MKT_CD"=EXCLUDED."MKT_CD","CNTRY_CD"=EXCLUDED."CNTRY_CD","CURR_CD"=EXCLUDED."CURR_CD",
 "DATA_SRC_CD"=EXCLUDED."DATA_SRC_CD","SRC_SYMBOL"=EXCLUDED."SRC_SYMBOL","DFLT_YN"=EXCLUDED."DFLT_YN",
 "USE_YN"='Y',"DEL_YN"='N',"UPD_DTTM"=CURRENT_TIMESTAMP,"UPD_USR_ID"='SYSTEM';
