CREATE TABLE "TB_INV_GRD" (
    "INV_GRD_CD" VARCHAR(10) PRIMARY KEY,
    "INV_GRD_NM" VARCHAR(50) NOT NULL,
    "TGT_WGT" NUMERIC(6,3) NOT NULL,
    "SORT_NO" INTEGER NOT NULL,
    "USE_YN" CHAR(1) NOT NULL DEFAULT 'Y',
    "RMK" VARCHAR(500),
    "CRT_DT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPD_DT" TIMESTAMP
);

COMMENT ON TABLE "TB_INV_GRD" IS '투자등급별 목표비중 설정';
COMMENT ON COLUMN "TB_INV_GRD"."INV_GRD_CD" IS '투자등급 코드';
COMMENT ON COLUMN "TB_INV_GRD"."INV_GRD_NM" IS '투자등급 명칭';
COMMENT ON COLUMN "TB_INV_GRD"."TGT_WGT" IS '종목별 목표비중';
COMMENT ON COLUMN "TB_INV_GRD"."SORT_NO" IS '투자 우선순위 및 정렬순서';
COMMENT ON COLUMN "TB_INV_GRD"."USE_YN" IS '사용 여부';

CREATE TABLE "TB_ACCT_ITEM_INV_STG" (
    "ACCT_ID" BIGINT NOT NULL,
    "ITEM_CD" VARCHAR(30) NOT NULL,
    "ITEM_CLS_CD" VARCHAR(20),
    "INV_GRD_CD" VARCHAR(10) NOT NULL,
    "IDX_CD" VARCHAR(30),
    "USE_YN" CHAR(1) NOT NULL DEFAULT 'Y',
    "RMK" VARCHAR(500),
    "CRT_DT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPD_DT" TIMESTAMP,

    CONSTRAINT "PK_ACCT_ITEM_INV_STG"
        PRIMARY KEY ("ACCT_ID", "ITEM_CD"),

    CONSTRAINT "FK_ACCT_ITEM_INV_STG_GRD"
        FOREIGN KEY ("INV_GRD_CD")
        REFERENCES "TB_INV_GRD"("INV_GRD_CD")
);
