DROP INDEX IF EXISTS "IDX_TB_STK_01";
ALTER TABLE "TB_STK" DROP CONSTRAINT IF EXISTS "UK_TB_STK_02";
ALTER TABLE "TB_STK" DROP COLUMN "TICKER";
COMMENT ON COLUMN "TB_STK"."STK_CD" IS '국내 종목코드 또는 해외주식 티커로 사용하는 시스템 종목 고유 코드';

