DROP VIEW IF EXISTS tb_reg_buy;

ALTER TABLE "TB_CASH_HIS" DROP CONSTRAINT IF EXISTS "FK_TB_CASH_HIS_02";
DROP INDEX IF EXISTS "IDX_TB_CASH_HIS_02";
ALTER TABLE "TB_CASH_HIS"
    ADD COLUMN "REG_BUY_ACCT_TP" VARCHAR(20),
    ADD COLUMN "REG_BUY_STK_CD" VARCHAR(30);
UPDATE "TB_CASH_HIS" h
SET "REG_BUY_ACCT_TP"=r."ACCT_TP", "REG_BUY_STK_CD"=r."STK_CD"
FROM "TB_REG_BUY" r
WHERE h."REG_BUY_ID"=r."REG_BUY_ID";
ALTER TABLE "TB_CASH_HIS" DROP COLUMN "REG_BUY_ID";

ALTER TABLE "TB_REG_BUY" DROP CONSTRAINT IF EXISTS "PK_TB_REG_BUY";
ALTER TABLE "TB_REG_BUY" DROP CONSTRAINT IF EXISTS "UK_BUY_SET_01";
ALTER TABLE "TB_REG_BUY" DROP COLUMN "REG_BUY_ID";
ALTER TABLE "TB_REG_BUY" ADD CONSTRAINT "PK_TB_REG_BUY" PRIMARY KEY ("ACCT_TP","STK_CD");

ALTER TABLE "TB_CASH_HIS" ADD CONSTRAINT "FK_TB_CASH_HIS_02"
    FOREIGN KEY ("REG_BUY_ACCT_TP","REG_BUY_STK_CD")
    REFERENCES "TB_REG_BUY"("ACCT_TP","STK_CD") ON UPDATE CASCADE;
CREATE INDEX "IDX_TB_CASH_HIS_02" ON "TB_CASH_HIS"("REG_BUY_ACCT_TP","REG_BUY_STK_CD");

CREATE VIEW tb_reg_buy AS
SELECT "ACCT_TP" AS account_type,"STK_CD" AS stock_code,"STK_NM" AS stock_name,
 "CYCLE_TP" AS cycle_type,"WEEK_DAY" AS day_of_week,"MONTH_DAY" AS day_of_month,
 "AMT" AS amount,"QTY" AS quantity,"ACTV_YN" AS active_yn,"PAUSE_RSN" AS pause_reason,
 "START_DT" AS start_date,"END_DT" AS end_date,"REG_DT" AS created_at,"MOD_DT" AS updated_at
FROM "TB_REG_BUY";

COMMENT ON COLUMN "TB_CASH_HIS"."REG_BUY_ACCT_TP" IS '관련 정기매수 계좌유형';
COMMENT ON COLUMN "TB_CASH_HIS"."REG_BUY_STK_CD" IS '관련 정기매수 종목코드';

