-- Replace the S&P 500 ETF used by the pension account on every account-based screen.
-- Historical market prices remain attached to their original stock; pension-specific
-- decisions and plans are moved so their account tabs consistently show the new ETF.

INSERT INTO "TB_STK_SET" (
    "ACCT_TP", "STK_CD", "STK_GRD", "TGT_WGT", "BM_CD", "REG_DT", "MOD_DT",
    "MKT_CD", "WGT_SCR", "MIN_INV_AMT", "MAX_INV_AMT", "MAX_INC_MULT"
)
SELECT
    "ACCT_TP", '360750', "STK_GRD", "TGT_WGT", "BM_CD", "REG_DT", CURRENT_TIMESTAMP,
    "MKT_CD", "WGT_SCR", "MIN_INV_AMT", "MAX_INV_AMT", "MAX_INC_MULT"
FROM "TB_STK_SET"
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800'
ON CONFLICT ("ACCT_TP", "STK_CD") DO NOTHING;

UPDATE "TB_ANALYSIS"
SET "STK_CD" = '360750',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

DELETE FROM "TB_STK_SET"
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_HOLD"
SET "STK_CD" = '360750',
    "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP,
    "UPD_USR_ID" = 'SYSTEM',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_REG_BUY"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500',
    "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP,
    "UPD_USR_ID" = 'SYSTEM',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_STK_DEC" d
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500'
FROM "TB_ACCT" a
WHERE d."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND d."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_ADD_BUY" b
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750')
FROM "TB_ACCT" a
WHERE b."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND b."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_REBUY" r
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750')
FROM "TB_ACCT" a
WHERE r."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND r."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_REBAL_ITEM" i
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP
FROM "TB_ACCT" a
WHERE i."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND i."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_BRF_STK"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_INV_EXEC"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500'
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';
