-- Replace the S&P 500 ETF used by the pension account on every account-based screen.
-- Historical market prices remain attached to their original stock; pension-specific
-- decisions and plans are moved so their account tabs consistently show the new ETF.

ALTER TABLE "TB_ANALYSIS" DROP CONSTRAINT "FK_ANALYSIS_01";
ALTER TABLE "TB_STK_SET" DROP CONSTRAINT "FK_STK_SET_01";

UPDATE "TB_HOLD"
SET "STK_CD" = '360750',
    "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP,
    "UPD_USR_ID" = 'SYSTEM',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_STK_SET"
SET "STK_CD" = '360750',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_ANALYSIS"
SET "STK_CD" = '360750',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

ALTER TABLE "TB_STK_SET" ADD CONSTRAINT "FK_STK_SET_01"
    FOREIGN KEY ("ACCT_TP", "MKT_CD", "STK_CD")
    REFERENCES "TB_HOLD"("ACCT_TP", "MKT_CD", "STK_CD") ON DELETE CASCADE;
ALTER TABLE "TB_ANALYSIS" ADD CONSTRAINT "FK_ANALYSIS_01"
    FOREIGN KEY ("ACCT_TP", "MKT_CD", "STK_CD")
    REFERENCES "TB_HOLD"("ACCT_TP", "MKT_CD", "STK_CD") ON DELETE CASCADE;

UPDATE "TB_REG_BUY"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500',
    "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP,
    "UPD_USR_ID" = 'SYSTEM',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_STK_DEC" d
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500'
FROM "TB_ACCT" a
WHERE d."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND d."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_ADD_BUY" b
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750')
FROM "TB_ACCT" a
WHERE b."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND b."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_REBUY" r
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750')
FROM "TB_ACCT" a
WHERE r."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND r."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_REBAL_ITEM" i
SET "STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '360750'),
    "UPD_DTTM" = CURRENT_TIMESTAMP
FROM "TB_ACCT" a
WHERE i."ACCT_ID" = a."ACCT_ID"
  AND a."ACCT_TP" = 'PENSION'
  AND i."STK_ID" = (SELECT "STK_ID" FROM "TB_STK" WHERE "MKT_CD" = 'KO' AND "STK_CD" = '379800');

UPDATE "TB_BRF_STK"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500',
    "MOD_DT" = CURRENT_TIMESTAMP
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';

UPDATE "TB_INV_EXEC"
SET "STK_CD" = '360750',
    "STK_NM" = 'TIGER 미국S&P500'
WHERE "ACCT_TP" = 'PENSION'
  AND "STK_CD" = '379800';
