ALTER TABLE "TB_REG_BUY"
    ADD COLUMN "BUY_BASIS" VARCHAR(10) NOT NULL DEFAULT 'AMOUNT',
    ADD COLUMN "BUY_DAY_NOS" VARCHAR(100);

UPDATE "TB_REG_BUY"
SET "BUY_BASIS" = CASE
        WHEN COALESCE("QTY", 0) > 0 OR ("QTY" IS NULL AND "AMT" IS NULL AND COALESCE("BASE_QTY", 0) > 0) THEN 'QUANTITY'
        ELSE 'AMOUNT'
    END,
    "BUY_DAY_CD" = COALESCE(NULLIF("WEEK_DAY", ''), "BUY_DAY_CD"),
    "BUY_DAY_NOS" = COALESCE("MONTH_DAY", "BUY_DAY_NO", "BASE_MONTH_DAY")::TEXT;

ALTER TABLE "TB_REG_BUY" DROP CONSTRAINT IF EXISTS "CK_TB_REG_BUY_02";
ALTER TABLE "TB_REG_BUY" ADD CONSTRAINT "CK_TB_REG_BUY_02"
    CHECK ("BUY_DAY_CD" IS NULL OR "BUY_DAY_CD" ~ '^(MON|TUE|WED|THU|FRI)(,(MON|TUE|WED|THU|FRI))*$');
ALTER TABLE "TB_REG_BUY" ADD CONSTRAINT "CK_TB_REG_BUY_16"
    CHECK ("BUY_BASIS" IN ('AMOUNT','QUANTITY'));
ALTER TABLE "TB_REG_BUY" ADD CONSTRAINT "CK_TB_REG_BUY_17"
    CHECK ("BUY_DAY_NOS" IS NULL OR "BUY_DAY_NOS" ~ '^([1-9]|[12][0-9]|3[01])(,([1-9]|[12][0-9]|3[01]))*$');

COMMENT ON COLUMN "TB_REG_BUY"."BUY_BASIS" IS '정기매수 기준(AMOUNT:금액, QUANTITY:수량)';
COMMENT ON COLUMN "TB_REG_BUY"."BUY_DAY_NOS" IS '월 정기매수일 목록(쉼표 구분)';
