ALTER TABLE "TB_REG_BUY"
    ADD COLUMN "APPLIED_DAY_NOS" VARCHAR(100);

UPDATE "TB_REG_BUY"
   SET "APPLIED_DAY_NOS" = "MONTH_DAY"::VARCHAR
 WHERE "CYCLE_TP" = 'MONTHLY'
   AND "MONTH_DAY" IS NOT NULL;

ALTER TABLE "TB_REG_BUY"
    ADD CONSTRAINT "CK_TB_REG_BUY_APPLIED_DAY_NOS" CHECK (
        "APPLIED_DAY_NOS" IS NULL
        OR "APPLIED_DAY_NOS" ~ '^([1-9]|[12][0-9]|3[01])(,([1-9]|[12][0-9]|3[01]))*$'
    );

COMMENT ON COLUMN "TB_REG_BUY"."APPLIED_DAY_NOS"
    IS '현재 적용 월간 매수일 목록. 쉼표로 구분된 1~31일';
