CREATE TEMPORARY TABLE "TMP_REG_BUY_SCHEDULE" (
    "ACCT_TP" VARCHAR(20) NOT NULL,
    "STK_CD" VARCHAR(20) NOT NULL,
    "BUY_STS" VARCHAR(20) NOT NULL,
    "CYCLE_TP" VARCHAR(20),
    "WEEK_DAY" VARCHAR(100),
    "APPLIED_DAY_NOS" VARCHAR(100),
    "AMT" NUMERIC(20, 4),
    "QTY" NUMERIC(20, 6),
    PRIMARY KEY ("ACCT_TP", "STK_CD")
);

INSERT INTO "TMP_REG_BUY_SCHEDULE"
    ("ACCT_TP", "STK_CD", "BUY_STS", "CYCLE_TP", "WEEK_DAY", "APPLIED_DAY_NOS", "AMT", "QTY")
VALUES
    ('ISA','411060','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','069500','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','305720','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','471990','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','117700','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','487230','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','379800','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','144600','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('ISA','266420','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','161510','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','0023A0','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','139270','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','227550','ACTIVE','WEEKLY','TUE',NULL,NULL,1),
    ('ISA','160580','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','464310','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('ISA','329200','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('ISA','458730','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','0183J0','ACTIVE','WEEKLY','TUE',NULL,NULL,1),
    ('ISA','305080','ACTIVE','WEEKLY','TUE,FRI',NULL,NULL,1),
    ('ISA','0046A0','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','381180','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','466940','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','494670','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('ISA','302190','PAUSED',NULL,NULL,NULL,NULL,NULL),

    ('DOMESTIC','007340','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','105560','ACTIVE','WEEKLY','MON',NULL,1000,NULL),
    ('DOMESTIC','010120','ACTIVE','WEEKLY','FRI',NULL,1000,NULL),
    ('DOMESTIC','000660','ACTIVE','WEEKLY','MON',NULL,1000,NULL),
    ('DOMESTIC','001440','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','034020','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','058470','PAUSED',NULL,NULL,NULL,1000,NULL),
    ('DOMESTIC','083650','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','028050','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','005930','PAUSED',NULL,NULL,NULL,1000,NULL),
    ('DOMESTIC','032820','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','000100','ACTIVE','MONTHLY',NULL,'15',1000,NULL),
    ('DOMESTIC','014680','ACTIVE','MONTHLY',NULL,'15',1000,NULL),
    ('DOMESTIC','000720','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('DOMESTIC','298040','ACTIVE','MONTHLY',NULL,'15',1000,NULL),

    ('PENSION','411060','ACTIVE','WEEKLY','MON',NULL,NULL,1),
    ('PENSION','069500','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','305720','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','471990','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('PENSION','117700','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','0089D0','ACTIVE','WEEKLY','TUE',NULL,NULL,1),
    ('PENSION','144600','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','266420','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','161510','ACTIVE','WEEKLY','TUE',NULL,NULL,1),
    ('PENSION','455890','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','0023A0','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','0051G0','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','139270','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','227550','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('PENSION','463250','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','160580','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','464310','ACTIVE','MONTHLY',NULL,'7,23',NULL,1),
    ('PENSION','329200','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','360750','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','458730','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','0183J0','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','305080','ACTIVE','WEEKLY','WED',NULL,NULL,1),
    ('PENSION','0046A0','ACTIVE','WEEKLY','TUE',NULL,NULL,2),
    ('PENSION','381180','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','241180','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('PENSION','494670','ACTIVE','MONTHLY',NULL,'15',NULL,1),
    ('PENSION','302190','PAUSED',NULL,NULL,NULL,NULL,NULL),

    ('OVERSEAS','BOTZ','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','GEV','ACTIVE','WEEKLY','TUE,FRI',NULL,2000,NULL),
    ('OVERSEAS','HYDR','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','QQQ','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','SCHD','ACTIVE','WEEKLY','TUE,FRI',NULL,2000,NULL),
    ('OVERSEAS','SMH','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','SPY','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','VIG','ACTIVE','WEEKLY','TUE,FRI',NULL,2000,NULL),
    ('OVERSEAS','XLF','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','XLI','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','XLV','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','MSFT','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','BAC','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','BRK.B','ACTIVE','WEEKLY','TUE',NULL,20000,NULL),
    ('OVERSEAS','VRT','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','AVGO','ACTIVE','WEEKLY','TUE,FRI',NULL,2000,NULL),
    ('OVERSEAS','VST','ACTIVE','WEEKLY','TUE',NULL,7000,NULL),
    ('OVERSEAS','V','ACTIVE','WEEKLY','TUE',NULL,10000,NULL),
    ('OVERSEAS','SPCX','ACTIVE','WEEKLY','TUE',NULL,3000,NULL),
    ('OVERSEAS','ANET','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','AMZN','ACTIVE','DAILY',NULL,NULL,1500,NULL),
    ('OVERSEAS','IONQ','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','GOOGL','ACTIVE','WEEKLY','TUE,FRI',NULL,2000,NULL),
    ('OVERSEAS','ABBV','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','AAPL','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','NVDA','ACTIVE','WEEKLY','TUE,FRI',NULL,1500,NULL),
    ('OVERSEAS','WMT','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','INTC','ACTIVE','WEEKLY','TUE',NULL,2000,NULL),
    ('OVERSEAS','LLY','ACTIVE','WEEKLY','TUE',NULL,7000,NULL),
    ('OVERSEAS','JPM','ACTIVE','DAILY',NULL,NULL,1000,NULL),
    ('OVERSEAS','JNJ','PAUSED',NULL,NULL,NULL,NULL,NULL),
    ('OVERSEAS','CAT','ACTIVE','WEEKLY','TUE',NULL,10000,NULL),
    ('OVERSEAS','COST','ACTIVE','WEEKLY','TUE',NULL,10000,NULL),
    ('OVERSEAS','CEG','ACTIVE','DAILY',NULL,NULL,1500,NULL),
    ('OVERSEAS','PLTR','ACTIVE','MONTHLY',NULL,'7,23',7000,NULL),
    ('OVERSEAS','PLUG','PAUSED',NULL,NULL,NULL,NULL,NULL);

DO $$
DECLARE
    V_TARGET_COUNT INTEGER;
    V_MATCHED_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_TARGET_COUNT FROM "TMP_REG_BUY_SCHEDULE";

    SELECT COUNT(*) INTO V_MATCHED_COUNT
      FROM "TMP_REG_BUY_SCHEDULE" t
      JOIN "TB_REG_BUY" r
        ON r."ACCT_TP" = t."ACCT_TP"
       AND r."STK_CD" = t."STK_CD"
       AND r."DEL_YN" = 'N';

    IF V_TARGET_COUNT <> 102 OR V_MATCHED_COUNT <> V_TARGET_COUNT THEN
        RAISE EXCEPTION
            'Regular-buy schedule target mismatch: targets %, matched %',
            V_TARGET_COUNT,
            V_MATCHED_COUNT;
    END IF;
END $$;

UPDATE "TB_REG_BUY" r
   SET "BUY_STS" = t."BUY_STS",
       "ACTV_YN" = CASE WHEN t."BUY_STS" = 'ACTIVE' THEN 'Y' ELSE 'N' END,
       "USER_PAUSE_YN" = 'N',
       "CYCLE_TP" = COALESCE(t."CYCLE_TP", r."CYCLE_TP"),
       "WEEK_DAY" = CASE WHEN t."CYCLE_TP" IS NULL THEN r."WEEK_DAY" ELSE t."WEEK_DAY" END,
       "APPLIED_DAY_NOS" = CASE
           WHEN t."CYCLE_TP" IS NULL THEN r."APPLIED_DAY_NOS"
           ELSE t."APPLIED_DAY_NOS"
       END,
       "MONTH_DAY" = CASE
           WHEN t."CYCLE_TP" IS NULL THEN r."MONTH_DAY"
           WHEN t."APPLIED_DAY_NOS" IS NULL THEN NULL
           ELSE SPLIT_PART(t."APPLIED_DAY_NOS", ',', 1)::INTEGER
       END,
       "AMT" = t."AMT",
       "QTY" = t."QTY",
       "PAUSE_RSN" = CASE WHEN t."BUY_STS" = 'PAUSED' THEN '사용자 설정' ELSE NULL END,
       "MOD_DT" = CURRENT_TIMESTAMP
  FROM "TMP_REG_BUY_SCHEDULE" t
 WHERE r."ACCT_TP" = t."ACCT_TP"
   AND r."STK_CD" = t."STK_CD"
   AND r."DEL_YN" = 'N';

DO $$
DECLARE
    V_MISMATCH_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_MISMATCH_COUNT
      FROM "TMP_REG_BUY_SCHEDULE" t
      JOIN "TB_REG_BUY" r
        ON r."ACCT_TP" = t."ACCT_TP"
       AND r."STK_CD" = t."STK_CD"
       AND r."DEL_YN" = 'N'
     WHERE r."BUY_STS" IS DISTINCT FROM t."BUY_STS"
        OR (t."CYCLE_TP" IS NOT NULL AND r."CYCLE_TP" IS DISTINCT FROM t."CYCLE_TP")
        OR (t."CYCLE_TP" IS NOT NULL AND r."WEEK_DAY" IS DISTINCT FROM t."WEEK_DAY")
        OR (t."CYCLE_TP" IS NOT NULL AND r."APPLIED_DAY_NOS" IS DISTINCT FROM t."APPLIED_DAY_NOS")
        OR r."AMT" IS DISTINCT FROM t."AMT"
        OR r."QTY" IS DISTINCT FROM t."QTY";

    IF V_MISMATCH_COUNT <> 0 THEN
        RAISE EXCEPTION
            'Regular-buy schedule update verification failed: mismatches %',
            V_MISMATCH_COUNT;
    END IF;
END $$;
