import React, { FormEvent, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Market = { indexDrawdownPct:number; volatilityIndex:number; foreignNetBuy:number; institutionNetBuy:number; individualNetBuy:number; programNetBuy:number; usdKrwChangePct:number; us10yChangeBp:number; breadthPct:number; newsFearScore:number; aiCapexFatigueScore:number; earningsConfidenceScore:number; liquidityScore:number; dominantNarrative:string };
type Position = { account:string; code:string; name:string; minimumBuyAmount:number; maximumBuyAmount:number; profitLossPct:number; stockDrawdownPct:number; targetWeight:number; currentWeight:number; fundamentalScore:number; valuationScore:number; themeRiskScore:number; regularBuyEnabled:boolean };
type Decision = { decisionDate:string; market:{regime:string;marketScore:number;sentiment:{phase:string;sentimentRiskScore:number;confidence:number;structuralDamageRisk:boolean;reasons:string[];reversalSignals:string[]};reasons:string[]}; totalMinimumBuyAmount:number;totalRecommendedBuyAmount:number;newlyReservedCash:number;availableAdditionalBuyCash:number;stockDecisions:Array<{account:string;code:string;name:string;action:string;multiplier:number;minimumBuyAmount:number;recommendedBuyAmount:number;reservedCash:number;reasons:string[]}>;weeklyActions:string[];monthlyActions:string[] };

const labels:Record<string,string>={OVERHEATED:'과열',NORMAL:'정상',MILD_CORRECTION:'약한 조정',STRONG_CORRECTION:'강한 조정',CRASH_RISK:'붕괴 위험',GREED:'탐욕',OPTIMISM:'낙관',NEUTRAL:'중립',FATIGUE:'피로',FEAR:'공포',PANIC:'패닉',PAUSE:'매수 중단',REDUCE:'축소',KEEP_MINIMUM:'최소 유지',INCREASE:'증액',ADDITIONAL_BUY:'추가 매수',REBALANCE_SELL:'리밸런싱 매도'};
const fmt=(n:number)=>`${new Intl.NumberFormat('ko-KR').format(n)}원`;
const initialMarket:Market={indexDrawdownPct:-18,volatilityIndex:29,foreignNetBuy:-12000,institutionNetBuy:3000,individualNetBuy:9000,programNetBuy:-5000,usdKrwChangePct:1.2,us10yChangeBp:12,breadthPct:28,newsFearScore:75,aiCapexFatigueScore:80,earningsConfidenceScore:78,liquidityScore:65,dominantNarrative:'AI 투자 피로와 외국인 위험 축소'};
const emptyPosition=():Position=>({account:'종합',code:'',name:'',minimumBuyAmount:0,maximumBuyAmount:0,profitLossPct:0,stockDrawdownPct:0,targetWeight:0,currentWeight:0,fundamentalScore:50,valuationScore:50,themeRiskScore:50,regularBuyEnabled:true});
const first:Position={...emptyPosition(),code:'QQQ',name:'QQQ',minimumBuyAmount:4000,maximumBuyAmount:12000,profitLossPct:-12,stockDrawdownPct:-18,targetWeight:.08,currentWeight:.05,fundamentalScore:85,valuationScore:78,themeRiskScore:45};
const marketFields:Array<[keyof Market,string,string?]>=[['indexDrawdownPct','지수 고점 대비 등락률','%'],['volatilityIndex','변동성 지수'],['foreignNetBuy','외국인 순매수'],['institutionNetBuy','기관 순매수'],['individualNetBuy','개인 순매수'],['programNetBuy','프로그램 순매수'],['usdKrwChangePct','원·달러 변화율','%'],['us10yChangeBp','미 10년물 변화','bp'],['breadthPct','시장 확산도','%']];
const scores:Array<[keyof Market,string]>=[['newsFearScore','뉴스 공포'],['aiCapexFatigueScore','AI CAPEX 피로'],['earningsConfidenceScore','실적 신뢰도'],['liquidityScore','유동성']];
const positionNumbers:Array<[keyof Position,string,number]>=[['minimumBuyAmount','최소 매수금액',1],['maximumBuyAmount','최대 매수금액',1],['profitLossPct','손익률 (%)',.1],['stockDrawdownPct','고점 대비 등락률 (%)',.1],['targetWeight','목표비중 (0~1)',.01],['currentWeight','현재비중 (0~1)',.01],['fundamentalScore','펀더멘털 점수',1],['valuationScore','밸류에이션 점수',1],['themeRiskScore','테마 위험 점수',1]];
function Num({value,onChange,...p}:{value:number;onChange:(n:number)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>){return <input type="number" value={value} onChange={e=>onChange(Number(e.target.value))} {...p}/>}
function App(){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[cash,setCash]=useState(0),[market,setMarket]=useState(initialMarket),[positions,setPositions]=useState([first]),[result,setResult]=useState<Decision|null>(null),[prompt,setPrompt]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const marketSet=(k:keyof Market,v:number|string)=>setMarket(x=>({...x,[k]:v}));
 const posSet=(i:number,k:keyof Position,v:string|number|boolean)=>setPositions(x=>x.map((p,j)=>i===j?{...p,[k]:v}:p));
 const call=async(path:'decision'|'briefing-prompt')=>{setLoading(true);setError('');try{const r=await fetch(`/api/investment/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decisionDate:date,existingReservedCash:cash,market,positions})});if(!r.ok)throw new Error((await r.text())||`요청 실패 (${r.status})`);const data=await r.json();if(path==='decision'){setResult(data);setPrompt('');setTimeout(()=>document.querySelector('.results')?.scrollIntoView({behavior:'smooth'}),0)}else setPrompt(data.prompt??'')}catch(e){setError(e instanceof Error?e.message:'서버 요청 오류')}finally{setLoading(false)}};
 const submit=(e:FormEvent)=>{e.preventDefault();void call('decision')};
 return <main className="container">
  <header className="hero"><div><span className="eyebrow">INVESTMENT DECISION ENGINE</span><h1>투자 의사결정 브리핑</h1><p>시장 상황과 보유 종목을 입력해 정기매수 금액과 행동 신호를 계산합니다.</p></div><div className="status"><span/> API <code>/api/investment</code></div></header>
  <form onSubmit={submit}>
   <section className="panel overview"><div className="field"><label>판단 기준일</label><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>기존 추가매수 대기 현금</label><Num min={0} value={cash} onChange={setCash}/></div><div className="field wide"><label>주요 시장 내러티브</label><input required value={market.dominantNarrative} onChange={e=>marketSet('dominantNarrative',e.target.value)}/></div></section>
   <section className="panel"><Title no="01" text="시장 데이터" extra={<p>점수 항목은 0~100 범위입니다.</p>}/><div className="form-grid">{marketFields.map(([k,l,u])=><div className="field" key={k}><label>{l}<em>{u}</em></label><Num step="any" value={market[k] as number} onChange={v=>marketSet(k,v)}/></div>)}</div><div className="score-grid">{scores.map(([k,l])=><label className="score" key={k}><span>{l}<strong>{market[k]}</strong></span><input type="range" min="0" max="100" value={market[k] as number} onChange={e=>marketSet(k,Number(e.target.value))}/></label>)}</div></section>
   <section className="panel"><Title no="02" text="보유 종목" extra={<button type="button" className="secondary" onClick={()=>setPositions(x=>[...x,emptyPosition()])}>+ 종목 추가</button>}/><div className="positions">{positions.map((p,i)=><article className="position-card" key={i}><div className="position-head"><strong>종목 {i+1}</strong>{positions.length>1&&<button type="button" className="remove" onClick={()=>setPositions(x=>x.filter((_,j)=>i!==j))}>삭제</button>}</div><div className="position-grid">{(['account','code','name'] as const).map((k,j)=><div className="field" key={k}><label>{['계좌','종목코드','종목명'][j]}</label><input required value={p[k]} onChange={e=>posSet(i,k,e.target.value)}/></div>)}{positionNumbers.map(([k,l,s])=><div className="field" key={k}><label>{l}</label><Num step={s} value={p[k] as number} onChange={v=>posSet(i,k,v)}/></div>)}<label className="toggle"><input type="checkbox" checked={p.regularBuyEnabled} onChange={e=>posSet(i,'regularBuyEnabled',e.target.checked)}/><span/>정기매수 활성화</label></div></article>)}</div></section>
   {error&&<div className="error"><strong>요청 오류</strong><span>{error}</span></div>}<div className="actions"><button type="button" className="secondary large" disabled={loading} onClick={()=>void call('briefing-prompt')}>GPT 브리핑 프롬프트 생성</button><button className="primary large" disabled={loading}>{loading?'분석 중…':'투자 판단 실행'}</button></div>
  </form>
  {prompt&&<section className="panel prompt"><Title no="GPT" text="브리핑 프롬프트" extra={<button className="secondary" onClick={()=>navigator.clipboard.writeText(prompt)}>복사</button>}/><pre>{prompt}</pre></section>}
  {result&&<section className="results"><div className="result-heading"><div><span className="eyebrow">{result.decisionDate} ANALYSIS</span><h2>의사결정 결과</h2></div><span className={`regime ${result.market.regime}`}>{labels[result.market.regime]}</span></div><div className="metric-grid"><Metric l="시장 점수" v={`${result.market.marketScore}/100`}/><Metric l="심리 위험" v={`${result.market.sentiment.sentimentRiskScore}/100`}/><Metric l="권장 매수 합계" v={fmt(result.totalRecommendedBuyAmount)}/><Metric l="추가매수 가능 현금" v={fmt(result.availableAdditionalBuyCash)}/></div><div className="result-grid"><section className="panel"><Title text="시장 진단" extra={<span className="confidence">신뢰도 {result.market.sentiment.confidence}%</span>}/><p className="phase">투자 심리: <strong>{labels[result.market.sentiment.phase]}</strong>{result.market.sentiment.structuralDamageRisk&&<b>구조적 훼손 위험</b>}</p><ul>{[...result.market.reasons,...result.market.sentiment.reasons].map((x,i)=><li key={i}>{x}</li>)}</ul><h3>반전 확인 신호</h3><ul className="signals">{result.market.sentiment.reversalSignals.map(x=><li key={x}>{x}</li>)}</ul></section><section className="panel cash"><h2>자금 배분</h2><dl>{[['최소 매수 합계',result.totalMinimumBuyAmount],['권장 매수 합계',result.totalRecommendedBuyAmount],['새로 적립할 현금',result.newlyReservedCash],['총 추가매수 대기 현금',result.availableAdditionalBuyCash]].map(([l,v])=><div key={l as string}><dt>{l}</dt><dd>{fmt(v as number)}</dd></div>)}</dl></section></div>
   <section className="panel"><Title no="03" text="종목별 행동 신호"/><div className="decision-table"><table><thead><tr><th>종목</th><th>행동</th><th>배수</th><th>최소 매수</th><th>권장 매수</th><th>적립 현금</th><th>근거</th></tr></thead><tbody>{result.stockDecisions.map(s=><tr key={s.account+s.code}><td><strong>{s.name}</strong><small>{s.account} · {s.code}</small></td><td><span className={`action ${s.action}`}>{labels[s.action]}</span></td><td>{s.multiplier}×</td><td>{fmt(s.minimumBuyAmount)}</td><td><strong>{fmt(s.recommendedBuyAmount)}</strong></td><td>{fmt(s.reservedCash)}</td><td><ul>{s.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul></td></tr>)}</tbody></table></div></section>
   <div className="result-grid schedules">{[['주간 실행 항목',result.weeklyActions],['월간 실행 항목',result.monthlyActions]].map(([t,a])=><section className="panel" key={t as string}><h2>{t as string}</h2><ol>{(a as string[]).map((x,i)=><li key={i}>{x}</li>)}</ol></section>)}</div>
  </section>}
 </main>
}
function Title({no,text,extra}:{no?:string;text:string;extra?:React.ReactNode}){return <div className="section-title"><div>{no&&<span>{no}</span>}<h2>{text}</h2></div>{extra}</div>}
function Metric({l,v}:{l:string;v:string}){return <div className="metric"><span>{l}</span><strong>{v}</strong></div>}
createRoot(document.getElementById('root')!).render(<App/>);
